### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by davejduke** [fsnotify/fsnotify#559] opened 2023-03-02 10:52 UTC
fatal error: all goroutines are asleep - deadlock!

Seems to work ok when I monitor a few directories, but if I monitor anything that has a few thousand files I get fatal error: all goroutines are asleep - deadlock!

    goroutine 1 [chan receive]:
    github.com/fsnotify/fsnotify.(*Watcher).Add(0xc00015c000, {0xc0796b3020, 0x57})
            C:/Program Files/Go/bin/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_windows.go:237 +0x1b7

example code
  
	package main

	import (
		"fmt"
		"os"
		"path/filepath"

		"github.com/fsnotify/fsnotify"
	)

	//
	var watcher *fsnotify.Watcher

	// main
	func main() {

		// creates a new file watcher
		watcher, _ = fsnotify.NewWatcher()
		defer watcher.Close()

		// starting at the root of the project, walk each file/directory searching for
		// directories
		if err := filepath.Walk("/Users/dave duke/", watchDir); err != nil {
			fmt.Println("ERROR", err)
		}

		//
		done := make(chan bool)

		//
		fmt.Println("Watching")
		go func() {
			for {
				select {
				// watch for events
				case event := <-watcher.Events:
					fmt.Printf("EVENT! %#v\n", event)

					// watch for errors
				case err := <-watcher.Errors:
					fmt.Println("ERROR", err)
				}
			}
		}()

		<-done
	}

	// watchDir gets run as a walk func, searching for directories to add watchers to
	func watchDir(path string, fi os.FileInfo, err error) error {

		// since fsnotify can watch all the files in a directory, watchers only need
		// to be added to each nested directory
		if fi.Mode().IsDir() {
			return watcher.Add(path)
		}

		return nil
	}

**Comment by arp242** [comment] 2023-03-13 17:03
I think this may be a duplicate of #502?

**Comment by arp242** [comment] 2023-05-17 19:30
Closing for now as I assume it's a duplicate of the aforementioned issue; let me know if it's not and we can reopen.

**Closed by arp242** 2023-05-17 19:30 UTC
