### ISSUE TITLE
When remove a watching directory not triggered remove event

### ISSUE THREAD

**Issue by smuuupl** [fsnotify/fsnotify#592] opened 2023-11-03 06:17 UTC
### Describe the bug

Running directly works fine, but when use systemctl command run, remove the monitor directory does not triggered remove event.

### To Reproduce

[Unit]
Description=fsnotify-test
After=network-online.target remote-fs.target nss-lookup.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/bin/bash /home/fsnotify-test
ExecStop=/usr/bin/kill -s TERM $MAINPID
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

### Which operating system and version are you using?

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

### Which fsnotify version are you using?

1.7.0

### Did you try the latest main branch?

No

**Comment by arp242** [comment] 2023-11-03 07:27
You didn't post the code you're running and the *exact* actions you took to demonstrate the problem, so this can't be reproduced.

**Comment by smuuupl** [comment] 2023-11-03 08:20
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watchdir := os.Args[1]
	watch, _ := fsnotify.NewWatcher()
	w := Watch{
		watch: watch,
	}
	w.watchDir(watchdir)
	select {}
}

type Watch struct {
	watch *fsnotify.Watcher
}

func (w *Watch) watchDir(dir string) {
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if info.IsDir() {
			path, err := filepath.Abs(path)
			if err != nil {
				return err
			}
			err = w.watch.Add(path)
			if err != nil {
				return err
			}
		}
		return nil
	})
	log.Println("wacthing dir：", dir)
	go func() {
		for {
			select {
			case ev := <-w.watch.Events:
				fmt.Println("event:", ev)
			case err := <-w.watch.Errors:
				{
					fmt.Println("error : ", err)
					return
				}
			}
		}
	}()
}

**Comment by smuuupl** [comment] 2023-11-03 08:24
package main

import (
"fmt"
"log"
"os"
"path/filepath"

"github.com/fsnotify/fsnotify"
)

func main() {
watchdir := os.Args[1]
watch, _ := fsnotify.NewWatcher()
w := Watch{
watch: watch,
}
w.watchDir(watchdir)
select {}
}

type Watch struct {
watch *fsnotify.Watcher
}

func (w *Watch) watchDir(dir string) {
filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
if info.IsDir() {
path, err := filepath.Abs(path)
if err != nil {
return err
}
err = w.watch.Add(path)
if err != nil {
return err
}
}
return nil
})
log.Println("wacthing dir：", dir)
go func() {
for {
select {
case ev := <-w.watch.Events:
fmt.Println("event:", ev)
case err := <-w.watch.Errors:
{
fmt.Println("error : ", err)
return
}
}
}
}()
}

**Comment by arp242** [comment] 2023-11-03 10:13
> and the exact actions you took to demonstrate the problem

I need to know exactly what you did, what you clicked, what commands you ran.

**Comment by MrEcco** [comment] 2024-03-05 22:00
I can reproduce it, and after a little investigation, I probably found what happen... Seem like the nature of this issue is around cgroups, chroots, bind mounts, or pid namespaces (because all of them may be related to both `systemd` and `containerd`). I found that in the docker container when you remove a file on the bind-mounted filesystem, when you do it within the container (via docker exec) it produces remove events, but in case of removing from the host system, it doesn't.

Steps to reproduce (conceptual):
- main terminal: `docker run --rm -it --name mycontainer -v $(pwd)/mybinddir:/data golang:1.20-alpine fsnotidy-test /data`
- second terminal: `docker exec -it mycontainer bash -c 'touch /data/123.txt && rm /data/123.txt'`
- check log of the main terminal and you will see CREATE and REMOVE events
- second terminal: `touch mybinddir/123.txt && rm mybinddir/123.txt`
- check log of the main terminal and you will see only CREATE event

@smuuupl Could you please try to start your systemd unit in the user mode? If it works then it means that there are some relations to cgroups. Or please provide the original unit file. If you watch directory with `bind` mount, please mention it too.

**Comment by arp242** [comment] 2024-04-03 12:29
> when you remove a file on the bind-mounted filesystem, when you do it within the container (via docker exec) it produces remove events, but in case of removing from the host system, it doesn't.

That seems a different issue. fsnotify just reads the kernel events – it's actually fairly straight-forward. If there are no events, then, well, there are no events for fsnotify to read from the kernel. To be honest I don't really know the full story on how this al fits together with namespaces and cgroups and whatnot, but I don't think there is much we can do about it on our end, other than perhaps document it and implement a polling watcher.

Or maybe it's not a different issue – OP never got back with a clear description of the problem, so closing this.

**Closed by arp242** 2024-04-03 12:29 UTC
Labels: bug, linux, need-feedback
