### ISSUE TITLE
Read event doubles on Windows 10

### ISSUE THREAD

**Issue by edwvee** [fsnotify/fsnotify#250] opened 2018-06-07 21:18 UTC
Simple app:
```go
func main() {
	folder := os.Args[1]

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	err = watcher.Add(folder)
	if err != nil {
		log.Fatal(err)
	}
	for {
		select {
		case event := <-watcher.Events:
			log.Println("event:", event)
			if event.Op&fsnotify.Write == fsnotify.Write {
				log.Println("modified file:", event.Name)
			}
		case err := <-watcher.Errors:
			log.Println("error:", err)
		}
	}
}
```
Starting it like:
myapp.exe H:\folder

When i change something in file, or add a new it prints:
2018/06/08 00:09:04 event: "H:\\folder\\123.txt": WRITE
2018/06/08 00:09:04 modified file: H:\folder\123.txt
2018/06/08 00:09:04 event: "H:\\folder\\123.txt": WRITE
2018/06/08 00:09:04 modified file: H:\folder\123.txt

What is wrong: library or my code?

**Comment by nektro** [comment] 2019-05-16 20:05
duplicate of 122

**Closed** 2019-10-05 21:33 UTC
