### ISSUE TITLE
Duplicate events for delete folder due to unix.IN_DELETE_SELF

### ISSUE THREAD

**Issue by Kimbsen** [fsnotify/fsnotify#299] opened 2019-07-25 10:29 UTC
```
uname -a
Linux kimsubuntu 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

When deleting a watched directory several inotify events are emitted.

For example using `inotifywait` to display ALL events:

    $ inotifywait -m -r root/
    Setting up watches.  Beware: since -r was given, this may take a while!
    Watches established.

    # mkdir root/test
        root/ CREATE,ISDIR                test
        root/ OPEN,ISDIR                  test
        root/ ACCESS,ISDIR                test
        root/ CLOSE_NOWRITE,CLOSE,ISDIR   test

    # rm -rf root/test
        root/        OPEN,ISDIR                   test
        root/test/   OPEN,ISDIR
        root/        ACCESS,ISDIR                 test
        root/test/   ACCESS,ISDIR
        root/        ACCESS,ISDIR                 test
        root/test/   ACCESS,ISDIR
        root/        CLOSE_NOWRITE,CLOSE,ISDIR    test
        root/test/   CLOSE_NOWRITE,CLOSE,ISDIR
        root/test/   DELETE_SELF
        root/        DELETE,ISDIR                 test

fsnotify doesn't receive/care about all of these due to the flags passed to `unix.InotifyAddWatch` but both the `DELETE_SELF` and `DELETE` events are converted to `fsnotify.REMOVE` events and both are emitted on watcher.Events.

Example using fsnotify in a test application:

    $ ./testapp root
    12:25:37.139029 started with root /home/kim/inotifytest/root

    # mkdir root/test
        12:25:41.834888 E => "/home/kim/inotifytest/root/test": CREATE

    # rm -rf root/test
        12:25:45.211957 E => "/home/kim/inotifytest/root/test": REMOVE
        12:25:45.212139 E => "/home/kim/inotifytest/root/test": REMOVE

I'm not sure if there is any case where only one of them will be emitted by the underlying inotify, but i think the DELETE event will be there in every case of flags passed to unix.InotifyAddWatch in fsnotify.

What I'm proposing is to not emit a `REMOVE` event for the underlying `IN_DELETE_SELF` event, possibly by adding it to the `func (e *Event) ignoreLinux(mask uint32) bool ` function.

**Comment by nathany** [comment] 2019-10-05 21:34
Thanks for the report.

**Comment by Asgoret** [comment] 2020-11-27 19:14
Same for linux when write file

**Comment by arp242** [comment] 2022-10-13 22:43
I cannot reproduce this behaviour (your example seems a bit wrong, as it's removing a subdirectory rather than the watched directory):

    % mkdir /tmp/xxx

    % fsnotify watch /tmp/xxx/ &
    00:36:09.8342 ready; press ^C to exit

    % rmdir /tmp/xxx
    00:36:21.3711   2 REMOVE        "/tmp/xxx"

This is with fsnotify 1.6.0, released today. Not sure when/how this was fixed, but removing the watched directory has been tested for a while and I haven't seen any failed.

I'll close this for now, but please get back to me if you're still having problems and we can reopen and investigate further.

**Comment by ttys3** [comment] 2022-12-25 15:17
this duplicated issue got back again due to DELETE_SELF and DELETE to directory been treated as the same in fsnotify

below tests will ouput:

```
fsnotify event: CREATE        "/tmp/watcher-test/abc"
fsnotify event: REMOVE        "/tmp/watcher-test/abc/def"
fsnotify event: REMOVE        "/tmp/watcher-test/abc"
fsnotify event: REMOVE        "/tmp/watcher-test/abc"
```

```go

func TestFsnotifyWatcherDeleteEventIsDuplicated(t *testing.T) {
	rootDirectory := "/tmp/watcher-test"
	os.RemoveAll(rootDirectory)
	os.Mkdir(rootDirectory, os.ModePerm)

	w, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}

	// in case of file change assign new index
	go func() {
		log.Info("start the event loop")
		for {
			select {
			// rename sub dir (dir WRITE) = event MOVE all sub dir files
			case event := <-w.Events:
				if event.Op&fsnotify.Create == fsnotify.Create {
					// log.Infof("add watch due to fsnotify: event CREATE: %v", event.Name)
					w.Add(event.Name)
				}
				fmt.Printf("fsnotify event: %s\n", event.String())
			case e := <-w.Errors:
				log.Errorf("fsnotify err: %#v", e)
			}
			time.Sleep(time.Millisecond * 10)
		}
	}()

	err = w.Add(rootDirectory)

	// just ignore os.ErrPermission, os.ErrNotExist, os.ErrInvalid or other errors
	if err != nil {
		log.Errorf("failed to add %s to the watcher, err: %s", rootDirectory, err.Error())
	} else {
		log.Infof("successfully added %s to the watcher, waiting for event ...", rootDirectory)
	}

	go func() {
		time.Sleep(time.Second * 3)
		os.MkdirAll(rootDirectory+"/abc/def/ghi", os.ModePerm)

		time.Sleep(time.Second * 3)
		os.RemoveAll(rootDirectory + "/abc")
	}()

	time.Sleep(time.Second * 30)

	err = w.Close()
	if err != nil {
		log.Errorf("watcher exited with error: %s", err)
	} else {
		log.Info("watcher exited with no error")
	}
}
```

**Comment by arp242** [comment] 2023-01-06 09:11
Thank you @ttys3; I haven't looked at it in detail yet, but I'll reopen the issue for now.

If you want to help then you can start by converting that test case to a more standard test case that we use, in e.g. `TestWatchRemove()`: https://github.com/fsnotify/fsnotify/blob/main/fsnotify_test.go#L660 – it's a lot easier to fix if there's a consistently failing test case.

**Closed** 2024-04-25 14:39 UTC
Labels: bug, linux
