### ISSUE TITLE
Is it possible to get an event that a dir/file is being viewed/opened in finder/explorer?

### ISSUE THREAD

**Issue by hu13** [fsnotify/fsnotify#319] opened 2019-12-17 21:09 UTC
Hi there,

I am working on an application that is interested not only on events that a file/dir has been modified but also if it is being `viewed/opened` by an external application like finder/explorer.

I am wondering if this is possible with certain enhancements to this library?
If so, can you point me in a direction that I can do more research on?

Thanks.

**Comment by cobolbaby** [comment] 2020-02-09 07:28
Keep an eye on the last access time.

System events also occur when the last access time changes

**Comment by arp242** [comment] 2022-07-24 11:33
READ events aren't supported right now.

I'm closing this one as a duplicate of #346, as it's fundamentally the same issue (add support for READ events).

**Closed by arp242** 2022-07-24 11:33 UTC
