### ISSUE TITLE
Atomic saves in text editors cause havoc, unable to watch individual files

### ISSUE THREAD

**Issue by nathany** [fsnotify/fsnotify#17] opened 2014-06-29 03:40 UTC
Reported by @robfig at https://github.com/howeyc/fsnotify/issues/91. See also https://github.com/nathany/looper/issues/14.

When editors use _atomic saves_ they Create a new file and then do a Rename rather than just a straight Write (like when touching a file).

Related issues:
- @mstum wanted to watch a single configuration file (https://github.com/howeyc/fsnotify/issues/94), and @iyf also had trouble watching a single file (https://github.com/howeyc/fsnotify/issues/37).
- If you Add a directory and then Remove a single file within the directory, the watcher will still report a Create due to atomic saves. https://code.google.com/p/go/issues/detail?id=7788

Dealing with text editors may be out of scope of fsnotify itself, but it could at least provide recommendations in the Wiki. 

@robfig also reported some other oddities, though those may be specific to kqueue on OS X.

**Comment by nathany** [comment] 2015-10-16 15:50
TextMate2 (OS X) use the exchangedata system call to perform the saves (not sure what that is). But Hugo users are having problems detecting saves: https://github.com/spf13/hugo/issues/1053#issuecomment-116778527

**Comment by arp242** [comment] 2022-07-24 11:50
Closing this as a duplicate of #372, since it's essentially the same problem. That issue is much newer, but also more comprehensive.

**Closed by arp242** 2022-07-24 11:50 UTC
