### ISSUE TITLE
I can not get notify in kubernetes pod

### ISSUE THREAD

**Issue by TXZdream** [fsnotify/fsnotify#300] opened 2019-08-01 08:50 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

kubernetes pod

### Please describe the issue that occurred.

I have two pods with the same volume mounted. I run fsnotify in pod a and operate files in pod b, in this case, I can not see any notify. But if I operate files in pod a, I can see output which tells me the changes of file.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

1. write a program which will print notify
1. create pod a and b using kubernetes and mount same pvc to a and b
1. start the programs above in pod a and watch the folder which the pv mount in
1. operate folder in pod b which the pv mount in

and you can not see any output in pod a

**Comment by xieyanker** [comment] 2019-08-17 09:37
@TXZdream Hello, I meet same issue on mips64 arch, I build the kubernetes on mips64el, but but the kubectl logs -f not work, it uses fsnotify's watch method. Have you resolved this issue?

**Comment by nathany** [comment] 2019-10-05 21:08
Please see #292. This seems a lot like that.

**Comment by arp242** [comment] 2022-07-30 13:06
Closing as duplicate of #292 for now, since it *seems* similar and the issue doesn't have enough information to reproduce it; "run k8s and do something with pods" isn't really enough: it should have a complete configuration from scratch and the code you used.

**Closed by arp242** 2022-07-30 13:06 UTC
Labels: documentation, help-wanted
