### ISSUE TITLE
Strange symlink behaviour

### ISSUE THREAD

**Issue by bo0rsh201** [fsnotify/fsnotify#210] opened 2017-06-09 13:29 UTC
Hello!
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```
```
go version go1.8 darwin/amd64
```
source code:
```
package main

import (
	"github.com/fsnotify/fsnotify"
	"log"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()
	err = watcher.Add("/Users/adenisov/test_dir")
	if err != nil {
		log.Fatal(err)
	}
	for {
		select {
		case ev := <-watcher.Events:
			log.Printf("Got event %+v", ev)
		case err := <-watcher.Errors:
			log.Printf("Got error %+v", err)
		}
	}
}
```
events:
```
touch file1
ln -s file1 current_file
touch file2
touch file3
unlink current_file && ln -s file3 current_file
```
```
$ go run test.go

# touch file1 - OK
2017/06/09 16:17:26 Got event "/Users/adenisov/test_dir/file1": CREATE 

# ln -s file1 current_file - OK
2017/06/09 16:17:37 Got event "/Users/adenisov/test_dir/current_file": CREATE

# ambiguous event for symlink, caused by touch file2
2017/06/09 16:17:42 Got event "/Users/adenisov/test_dir/current_file": CREATE

# touch file2 - OK
2017/06/09 16:17:42 Got event "/Users/adenisov/test_dir/file2": CREATE

# same problem, caused by touch file3
2017/06/09 16:17:48 Got event "/Users/adenisov/test_dir/current_file": CREATE

# touch file3 - OK
2017/06/09 16:17:48 Got event "/Users/adenisov/test_dir/file3": CREATE 

# unlink current_file doesn't trigger any event
# ln -s file3 current_file - OK
2017/06/09 16:18:07 Got event "/Users/adenisov/test_dir/current_file": CREATE 
```
The main question is:
Why I am not notified about symlink unlink event?
And why do I receive symlink CREATE event each time any file is created?
What do I do wrong?
P. S. thanks for nice library

**Comment by arp242** [comment] 2022-07-31 01:18
Closing as duplicate of #47

**Closed by arp242** 2022-07-31 01:18 UTC
Labels: bug, macOS
