### ISSUE TITLE
Request to have event type filtering method

### ISSUE THREAD

**Issue by AlanYiNew** [fsnotify/fsnotify#352] opened 2020-11-17 12:54 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: lsb_release -a

### Please describe the issue that occurred.
Is it possible to have fine grained control on interested events instead of watching all of them ? I read the api documentation and know what's your concernt. However, there is no way to extend the library to improve the efficency. In my situation, I would like to only watch create/move/delete event out of a large number of write event involved.

**Comment by bigTuxer** [comment] 2020-12-09 22:08
Hi,

it would be great to be able to define the events the watcher is looking for.  
if i use the example from your main readme.md file and try to filter the events like that:
```go
if event.Op&fsnotify.Create == fsnotify.Create {
  log.Println("Created file:", event.Name)
} else if event.Op&fsnotify.Remove == fsnotify.Remove {
  log.Println("Deleted file:", event.Name)
}
```
My litle test program has a  the cpu utilisation is by round about 36%  
If i use the linux command inotifywait and define the events create and delete, the cpu utilisation is by 0%.

My test program and inotifywait are observing the same path, there are many file changes in that directory.

When i modify the const agnosticEvents in the file inotify.go line 97 from:
```go
	const agnosticEvents = unix.IN_MOVED_TO | unix.IN_MOVED_FROM |
		unix.IN_CREATE | unix.IN_ATTRIB | unix.IN_MODIFY |
		unix.IN_MOVE_SELF | unix.IN_DELETE | unix.IN_DELETE_SELF
```
To:
```go
	const agnosticEvents = unix.IN_CREATE | unix.IN_DELETE
```
The cpu utilisation from my test program is by 0% like the linux command inotifywait.

I've tested that on:
```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by arp242** [comment] 2022-07-29 19:46
Closing as duplicate of #7.

**Closed by arp242** 2022-07-29 19:46 UTC
