### ISSUE TITLE
Events and errors spew out using the basic example

### ISSUE THREAD

**Issue by flexd** [fsnotify/fsnotify#140] opened 2016-04-20 21:37 UTC
This is the code I have, which is basically just [the example](https://godoc.org/github.com/fsnotify/fsnotify#example-NewWatcher) watcher from godoc.

I am on Debian 8 (Jessie), running a 3.16 kernel. Let me know if you need  any more info.

```go
go func() {                                                     
    // Watch for changes and call LoadPosts                     
    watcher, err := fsnotify.NewWatcher()                       
    if err != nil {                                             
        log.Fatal(err)                                          
    }                                                           
    defer watcher.Close()                                       
                                                                
    go func() {                                                 
        for {                                                   
            select {                                            
            case event := <-watcher.Events:                     
                log.Println("event:", event)                    
                if event.Op&fsnotify.Write == fsnotify.Write {  
                    log.Println("modified file:", event.Name)   
                }                                               
            case err := <-watcher.Errors:                       
                log.Println("error:", err)                      
            }                                                   
        }                                                       
    }()                                                         
                                                                
    err = watcher.Add("./posts")                                
    if err != nil {                                             
        log.Fatal(err)                                          
    }                                                           
}()                                                             
```

And the output of this is and endless stream of this:
```
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 event: "": 
2016/04/20 23:34:30 error: <nil>
2016/04/20 23:34:30 error: <nil>
```

**Comment by flexd** [comment] 2016-04-20 21:47
I am on Go 1.5.3 at the moment, if that matters. I have not been good at keeping up with updates :)

**Comment by nathany** [comment] 2016-04-20 22:03
From Slack, @flexd reports the same issue with v1.2.11, so this isn't a regression with the new syscall dependency in 1.3.

**Comment by Depado** [comment] 2016-05-05 22:55
Same here on Archlinux using a 4.5.1 kernel. Running with Go 1.6. Exact same output, it looks like the files are not watched (tried with a directory and with a single file).

**Comment by ppknap** [comment] 2016-05-06 19:39
the code provided by @flexd is not basically the code from godoc example. There are two goroutines here. The first one creates a watcher, runs second goroutine that is responsible for catching events, then adds `./post` folder/file and returns **immediately**. This calls `defer watcher.Close()` function which closes both `watcher.Events` and `watcher.Errors` channels. That's the reason why you receive an endless stream of zero values.

**Comment by nathany** [comment] 2016-05-06 20:20
@ppknap Good call.

@Depado does your code do a similar thing or do you have a different cause?

Maybe we can improve the documentation or FAQ to indicate that watcher.Close() should only be called when you're done watching, not in a defer in a function call.

**Comment by Depado** [comment] 2016-05-07 00:29
I think that should indeed fix the problem. I didn't try but that's a good call. I think I made the same mistake as @flexd.

**Comment by flexd** [comment] 2016-05-07 13:00
Oops. Not sure how we missed this.. thanks for spotting that @ppknap :D

**Comment by nathany** [comment] 2016-05-10 02:30
Closing this. If you have any suggestions for making this more clear in the examples or documentation, feel free to reopen it or open a new issue.

**Closed by nathany** 2016-05-10 02:30 UTC
Labels: investigate, Linux (inotify)
