### ISSUE TITLE
False Positive REMOVE Events with Git Sync

### ISSUE THREAD

**Issue by suddendust** [fsnotify/fsnotify#453] opened 2022-05-16 08:33 UTC
**Describe the bug**

We have an application that evaluates alerts rules specified as alert files in Github. We use `git-sync` side-car to sync these rules to a shared K8s volume. The application adds a `fsNotify` watch to this directory during bootstrap, and responds to its events. For example, if a PR is merged upstream that deletes an alert-rule file, a `REMOVE` event is sent and the application remove all the rules in that file.

<img width="1100" alt="Screenshot 2022-05-16 at 1 32 40 PM" src="https://user-images.githubusercontent.com/84911643/168546817-4bb3a806-4fe9-4abd-9331-7633511cf732.png">

However, I have observed that the application is receiving `REMOVE` events for all alert-rule files inside the directory being watched. This happens after it has run for some time after bootstrap. Since this happens for all alert-rule files, the application ultimately stops evaluating any alerts.

Here are some logs. As soon as I receive the `REMOVE` event, I log the contents of entire directory. I receive the event for the file name present in the last log (`ignoring removing rules`):

```
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].yaml"}
**{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"test-file-obsv-700.yaml"}**
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"resources"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].png"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted].png"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted]"}
{"level":"DEBUG","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:174","message":"walked file name","fileName":"[redacted]yaml"}
**{"level":"INFO","time":"2022-05-16T08:20:27.162Z","caller":"orchestrator/orchestrator.go:180","message":"ignoring removing rules","file":"/rules/{$commit}/production/test-file-obsv-700.yaml"}**

```
As you can see, the application received a `REMOVED` event for `test-file-obsv-700.yaml` although it is present in the directory.

**To Reproduce**

Not exactly sure how this can be reproduced. It should not need this entire setup though.

**Expected behavior**
I am not expecting any REMOVE events as no alert-rule files are being deleted upstream.

**Which operating system and version are you using?**

K8s, image is based on `golang-1.17-alpine` for Linux.

**Additional context**

None

**Comment by arp242** [comment] 2022-07-21 15:58
Are you sure the system doesn't remove files internally somehow? For example when files are updated this can happen.

Other than that, your setup is pretty unclear and not something I can reproduce. For this to be actionable you need to narrow things down a bit, and ideally provide a way to reproduce the problem. Even *if* I would be inclined to try and reproduce your setup, it would be hard as your description isn't too detailed and there is no code, configuration, or anything else.

**Comment by suddendust** [comment] 2022-07-22 04:52
@arp242 I'll add more information.

**Comment by arp242** [comment] 2022-08-06 18:12
I'll close this for the time being because reproducible right now and not clear if this a problem in fsnotify. Feel free to get back with more details and we can reopen, investigate, and (hopefully) fix any issues.

**Closed by arp242** 2022-08-06 18:12 UTC
Labels: linux, need-feedback
