### ISSUE TITLE
No event triggered when link removed

### ISSUE THREAD

**Issue by felipejfc** [fsnotify/fsnotify#47] opened 2014-10-04 23:45 UTC
If you create a link inside a folder that is being watched, a create event is triggered, but if you remove this link, no event is triggered

**Comment by arp242** [comment] 2022-07-31 01:14
I can confirm this happens on both macOS and FreeBSD.

**Comment by arp242** [comment] 2022-07-31 01:25
The reason is that kqueue.go does:

        // Follow Symlinks
        // Unfortunately, Linux can add bogus symlinks to watch list without
        // issue, and Windows can't do symlinks period (AFAIK). To  maintain
        // consistency, we will act like everything is fine. There will simply
        // be no file events for broken symlinks.
        // Hence the returns of nil on errors.
        if fi.Mode()&os.ModeSymlink == os.ModeSymlink {
            name, err = filepath.EvalSymlinks(name)

So the link is never added to the watch list.

**Comment by arp242** [comment] 2022-08-03 23:08
Closing this as a duplicate of #227, since it's caused by the same issue and that describes the root cause better.

**Closed by arp242** 2022-08-03 23:08 UTC
Labels: bug, macOS, freebsd
