### ISSUE TITLE
Removing recursive watches

### ISSUE THREAD

**Issue by cespare** [fsnotify/fsnotify#41] opened 2014-09-12 02:44 UTC
I've implemented recursive watching for a few different projects. The way I've basically done this is:
- Add a watch for the root dir
- When there's a `create` event, walk the created dir and add new watches for all `dirs`
- When there's a `remove` event, remove the watch for that dir

(I'm using fsnotify.v1.) I've realized that this isn't correct, because I don't delete the watches recursively. So I guess I need to keep track of the full tree of watches on my end as well? Maybe fsnotify could help out by exposing a 'delete all watches with this prefix' method or something.

Suggestions?

Additionally, #40 means that even if I could know all the dirs to remove watches for, I _still_ couldn't delete them.

**Comment by arp242** [comment] 2022-08-03 21:47
> fsnotify does not let me do this without keeping track of all watches (i.e. duplicating w.watches) myself.

There is now the `WatchList()` method, so this at least is no longer needed.

Better support for e.g. `Watcher.Remove("dir/...")` is something I'll pick up as part of #18, so closing this as a duplicate of that one.

**Closed by arp242** 2022-08-03 21:47 UTC
Labels: feature
