### ISSUE TITLE
The fsnotify.WRITE and fsnotify.CHMOD events are generated when a file is changed in arm architecture

### ISSUE THREAD

**Issue by cyclinder** [fsnotify/fsnotify#421] opened 2022-01-19 09:07 UTC
Before reporting an issue, please ensure you are using the latest release of `fsnotify`, and please
search for existing issue to avoid duplicates.

**Describe the bug**

[issue: https://github.com/kubernetes/kubernetes/issues/103500](https://github.com/kubernetes/kubernetes/issues/103500)

Under ARM64 environment, POD log parameter is the wireless cycle of log after Follow.  

I looked at the kubelet source code and found that kubelet watch for changes to the container log file via fsnotify and outputs the new log to the terminal when new logs are generated.

https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/kuberuntime/logs/logs.go#L438-L454

My guess is that fsnotify reported the events that did not meet expectations, causing the kubelet to re-read the entire log file each time (original log + new log), so what we see in the terminal is that the log keeps polling for a refresh.

and I extracted the key code from the kubelet and verified the issue on the arm64 architecture, but the same code works fine on amd64.

on arm64, fsnotify intermittently reports CHMOD event events, even if there are no new changes to this file, as shown below:
```bash
I0119 16:28:57.247735  904671 main.go:416] fsnotify.Chmod
I0119 16:28:57.754465  904671 main.go:404] fsnotify.Write
I0119 16:28:59.720545  904671 main.go:416] fsnotify.Chmod
I0119 16:28:59.779180  904671 main.go:416] fsnotify.Chmod
I0119 16:29:00.435542  904671 main.go:416] fsnotify.Chmod
I0119 16:29:00.493033  904671 main.go:416] fsnotify.Chmod
I0119 16:29:02.203653  904671 main.go:416] fsnotify.Chmod
I0119 16:29:02.259917  904671 main.go:416] fsnotify.Chmod
I0119 16:29:07.215793  904671 main.go:416] fsnotify.Chmod
I0119 16:29:07.276046  904671 main.go:416] fsnotify.Chmod
I0119 16:29:10.485498  904671 main.go:416] fsnotify.Chmod
I0119 16:29:10.545103  904671 main.go:416] fsnotify.Chmod
I0119 16:29:10.604148  904671 main.go:416] fsnotify.Chmod
```
on amd64, it work well:
```
[root@master kubelet]# go run main.go
I0119 16:36:53.251494 2949984 main.go:534] WebServer Starting on 127.0.0.1:18080...
I0119 16:37:12.500778 2949984 main.go:286] success to watch file "/var/lib/docker/containers/bd965f51b1d1a255262e287e0b6a78e322f68c198991b28a7563e21caf28677f/bd965f51b1d1a255262e287e0b6a78e322f68c198991b28a7563e21caf28677f-json.log"
I0119 16:37:18.223509 2949984 main.go:404] fsnotify.Write
I0119 16:37:26.417523 2949984 main.go:404] fsnotify.Write
```
Can anyone help me?  I don't know what's causing this，Thanks!

**To Reproduce**

<img width="1439" alt="wecom-temp-2f08e0a10e1f8406a39e5278f360fa90" src="https://user-images.githubusercontent.com/59680092/150140165-ad190887-c856-4f8e-946c-b8003f9d4f67.png">

**Expected behavior**

When the file changes, fsnotify reports the correct event instead of always reporting the CHMOD event

**Which operating system and version are you using?**

```bash
[root@dce-18-18-10-202 kubelet-fsnotify]# uname -a
Linux dce-18-18-10-202 4.19.90-23.8.v2101.ky10.aarch64 #1 SMP Mon May 17 17:07:38 CST 2021 aarch64 aarch64 aarch64 
GNU/Linux
```

**Additional context**
If applicable, add screenshots or a code sample to help explain your problem.

**Comment by giuseppe** [comment] 2022-03-03 08:42
do you have a reproducer you can share?

**Comment by cyclinder** [comment] 2022-03-03 10:00
@giuseppe  please refer to:  https://github.com/kubernetes/kubernetes/pull/107634#issuecomment-1057681683

**Comment by cyclinder** [comment] 2022-03-03 10:01
@giuseppe  please refer to:  https://github.com/kubernetes/kubernetes/pull/107634#issuecomment-1057681683

**Comment by giuseppe** [comment] 2022-03-03 11:34
could you please strace the command on arm64 to see what happens?  If you run just the `test()` function, does it end up in a loop with CHMOD notifications?

**Comment by pacoxu** [comment] 2022-09-20 10:07
This should be a bug.
We meet the same issue in Kylin/arm64.

**Comment by arp242** [comment] 2022-09-20 19:38
It may have been resolved in the latest `main`, so you can try that @pacoxu.

I don't have an arm(64) system, so it is hard to investigate and fix for me. So if it's not fixed in that, by far the quickest way to get it resolved would be to investigate yourself and see if you can fix it.

**Comment by cyclinder** [comment] 2022-09-21 03:01
Thanks @arp242 ,I will try to verify it using the latest fsnotify.

**Comment by saurori** [comment] 2022-10-06 17:11
I'm seeing this issue on arm64 Mac (14" M1 Pro) as well. Testing against [main branch](https://github.com/fsnotify/fsnotify/commit/89b4cf13a78441b79b86eeea2ff309bf95bdbf66).

<details>
    <summary>Testing using the sample code above</summary>

```shell
INFO[0000] success to watch file "123"                  
INFO[0002] file no change, wait 2 second                
INFO[0003] fsnotify.Write                               
INFO[0003] fsnotify.Chmod                               
INFO[0005] file no change, wait 2 second                
INFO[0007] file no change, wait 2 second                
INFO[0007] fsnotify.Chmod                               
INFO[0007] fsnotify.Write                               
INFO[0008] fsnotify.Chmod                               
INFO[0010] file no change, wait 2 second                
INFO[0012] file no change, wait 2 second 
```
</details>

The first `Write` + `Chmod` was from `echo 'hello' >> 123`. The second `Chmod` + `Write` + `Chmod` was editing and saving the file in Visual Studio Code.

**Comment by arp242** [comment] 2022-10-13 03:38
That just sounds like VSCode is generating these events @saurori; it happens especially with some more "complex" writes that some editors do. It certainly seems different from "fsnotify intermittently reports CHMOD event events, even if there are no new changes to this file", which is what was reporting in this issue.

**Comment by saurori** [comment] 2022-10-13 14:53
@arp242 possibly but I reported it because it's very similar behavior seen in [this comment](https://github.com/fsnotify/fsnotify/issues/421#issuecomment-1057974118) by OP.

**Comment by arp242** [comment] 2022-10-14 14:34
> @arp242 possibly but I reported it because it's very similar behavior seen in [this comment](https://github.com/fsnotify/fsnotify/issues/421#issuecomment-1057974118) by OP.

Yeah, but they did `echo hello >> 123` rather than write it with VSCode.

At any rate, Cirrus CI offers macOS M1 and Linux ARM64 CI machines; I tried setting it up yesterday but GitHub errors out if I try to add it; sent a support request for that. But hopefully we should have ARM platforms tested in the CI soon.

**Comment by saurori** [comment] 2022-10-14 14:35
@arp242 if you re-read my comment, I also did `echo` in addition to vscode write to show both scenarios.

**Comment by arp242** [comment] 2022-10-14 14:39
Oh right; oops. Either way, not much I can do about it now because I don't have access to any of that hardware. 

Does `go test` pass or fail for you by the way? If it can reproduced there it'll get picked up in the test runner and I have *some* chance of fixing it. If not, someone will have to add a failing test.

**Comment by saurori** [comment] 2022-10-14 14:52
Pulled latest `main` and ran `go test` but hit `too many open files` error:
```shell
--- FAIL: TestWatchStress (28.71s)
    fsnotify_test.go:1129: limiting files to 122780 due to max open files limit
    fsnotify_test.go:1138: createFiles: 000_000_000
    fsnotify_test.go:1138: createFiles: 000_010_000
    fsnotify_test.go:1138: createFiles: 000_020_000
    fsnotify_test.go:1138: createFiles: 000_030_000
    fsnotify_test.go:1138: createFiles: 000_040_000
    fsnotify_test.go:1138: createFiles: 000_050_000
    fsnotify_test.go:1138: createFiles: 000_060_000
    fsnotify_test.go:1138: createFiles: 000_070_000
    fsnotify_test.go:1138: createFiles: 000_080_000
    fsnotify_test.go:1138: createFiles: 000_090_000
    fsnotify_test.go:1138: createFiles: 000_100_000
    fsnotify_test.go:1138: createFiles: 000_110_000
    fsnotify_test.go:1138: createFiles: 000_120_000
    helpers_test.go:384: fsnotify.sendDirectoryChangeEvents: fcntl /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchStress3544888788/001: too many open files
    helpers_test.go:354: event stream was not closed after 10s
--- FAIL: TestWatchList (0.10s)
    fsnotify_test.go:1235: newWatcher: add "/var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchList2194012516/001": open /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchList2194012516/001: too many open files
    testing.go:1090: TempDir RemoveAll cleanup: open /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T: too many open files
FAIL
exit status 1
FAIL    github.com/fsnotify/fsnotify    36.123s
```

Setting `ulimit -n 12288`, then running `go test` I still get error:
```shell
--- FAIL: TestWatchStress (28.27s)
    fsnotify_test.go:1129: limiting files to 122780 due to max open files limit
    fsnotify_test.go:1138: createFiles: 000_000_000
    fsnotify_test.go:1138: createFiles: 000_010_000
    fsnotify_test.go:1138: createFiles: 000_020_000
    fsnotify_test.go:1138: createFiles: 000_030_000
    fsnotify_test.go:1138: createFiles: 000_040_000
    fsnotify_test.go:1138: createFiles: 000_050_000
    fsnotify_test.go:1138: createFiles: 000_060_000
    fsnotify_test.go:1138: createFiles: 000_070_000
    fsnotify_test.go:1138: createFiles: 000_080_000
    fsnotify_test.go:1138: createFiles: 000_090_000
    fsnotify_test.go:1138: createFiles: 000_100_000
    fsnotify_test.go:1138: createFiles: 000_110_000
    fsnotify_test.go:1138: createFiles: 000_120_000
    helpers_test.go:384: fsnotify.sendDirectoryChangeEvents: fcntl /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchStress2856273064/001: too many open files
    helpers_test.go:354: event stream was not closed after 10s
--- FAIL: TestWatchList (0.10s)
    fsnotify_test.go:1235: newWatcher: add "/var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchList3578293320/001": open /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T/TestWatchList3578293320/001: too many open files
    testing.go:1090: TempDir RemoveAll cleanup: open /var/folders/kz/2bt8cg551px1ml0ty89n3vfc0000gn/T: too many open files
FAIL
exit status 1
FAIL	github.com/fsnotify/fsnotify	35.637s
```

**Comment by arp242** [comment] 2022-10-14 14:54
The "stress test" is a bit flaky at times; you probably need to increase the max open files to make it work well (see README). Most of the times I just skip it (you can use `go test -short` to skip it).

So if that's the only failing test then the tests actually pass.

**Comment by saurori** [comment] 2022-10-14 14:56
I think Mac OS has some hard limit on max open files, so increasing ulimit doesn't help.

Running `go test -short` passes:
```shell
PASS
ok  	github.com/fsnotify/fsnotify	10.562s
```

**Comment by arp242** [comment] 2022-10-14 15:25
Yes, you need to use sysctl.

Either way, I still think this is a very different issue; what was reported was:

> on arm64, fsnotify intermittently reports CHMOD event events, even if there are no new changes to this file, as shown below:

But you're actually doing *stuff* to the file. The whole example they provided in a follow-up comment is a bit of a red herring, because that too is doing *stuff* to the file. It also uses Linux/arm64, not darwin/arm64.

I suspected the *original issue* may just be some process doing things; that is, there are actually events being sent. But it's hard to be sure from here.

Your issue: I don't know... I just have a macOS QEMU VM, but that seems to work:

	[~/fsnotify]% go run ./cmd/fsnotify watch /tmp/xxx &
	17:17:57.2205 ready; press ^C to exit

	[~/fsnotify]% echo asd >> /tmp/xxx/asd
	17:18:03.2299   1 CREATE        "/tmp/xxx/asd"
	[~/fsnotify]% echo asd >> /tmp/xxx/asd
	17:18:04.9993   2 WRITE         "/tmp/xxx/asd"
	[~/fsnotify]% echo asd >> /tmp/xxx/asd
	17:18:05.6646   3 WRITE         "/tmp/xxx/asd"
	[~/fsnotify]% echo asd >> /tmp/xxx/asd
	17:18:06.0105   4 WRITE         "/tmp/xxx/asd"

But I don't have an M1 machine. It may just be an issue of macOS version; I'm using 12.5 build 21G72.

Either way, if fsnotify reports a Chmod then *something* probably did issue a Chmod event from the underlying system's API; not sure if there's much we can do about it, and probably something you need to handle in your application. #7 will help with that.

**Comment by arp242** [comment] 2022-10-17 01:22
With #528 the CI now also runs in linux/arm64 and darwin/arm64, where it seems to work fine.

The inotify backend is pretty simple: unlike some other backends we never create our own events and it's little more than a wrapper to convert the events inotify send us to what we want to send on the channel. It might accidentally drop some events or have other issues, but erroneously generating events that weren't reported by the kernel is not something I can see happening.

I can't tell you what is sending these events; maybe kubernetes does something with these files, or something else on your system. I suspect these events are genuine and that *something* is causing these events to be sent; that this happens on arm64 isn't really all that important. But it's hard to be sure: it could also be a bug somewhere, but if it is, then it's probably in the Linux kernel.

One possibility is that there are still open file descriptors when files get removed (by any process). inotify will immediately generate a IN_ATTRIB event (fsnotify.Chmod), and then a IN_REMOVE (fsnotify.Remove) when the descriptor is closed. Or maybe something else is touching the file like some background process or some such; inotify(7) documents IN_ATTRIB as:

    IN_ATTRIB (*)
          Metadata changed—for example, permissions (e.g., chmod(2)),
          timestamps (e.g., utimensat(2)), extended attributes
          (setxattr(2)), link count (since Linux 2.6.25; e.g., for the
          target of link(2) and for unlink(2)), and user/group ID
          (e.g., chown(2)).

So the fsnotify.Chmod event doesn't map *exactly* to a "chmod" operation, but it's the closest thing we have and there isn't really any way we can do better. Maybe when #114 gets implemented it will be improved, but I haven't looked much at fanotify yet.

This is something kubernetes can handle better though. Looking at https://github.com/kubernetes/kubernetes/pull/107634 it seems it just unconditionally assumes a logfile was recreated on Chmod. In https://github.com/kubernetes/kubernetes/pull/73041#discussion_r248967000 it was mentioned that "I've seen the Chmod event coming from fsnotify instead of Rename or Create when the log file was replaced with rename(2)", but I can't really reproduce that, and other people mentioned they can't either. And even if I could reproduce it, unconditionally assuming a Chmod event made the file disappear would still be the wrong behaviour IMO.

---

My suggestion for kubernetes would be to:

- remove the Chmod event from the kubernetes handling, or handle it a bit smarter somehow. It's not really clear to me what problem having Chmod in there solved in the first place (I wasn't maintaining this in 2019), and it may have been fixed quite a while ago.

- watch the parent directory the file is in, rather than the file itself. Watching files is kind of tricky for a number of reasons and not something I would recommend doing in most cases. Watching the directory is usually more reliable.

And in general:

- You can try running `inotifywait -m /path/to/file/or/dir` and see what that does; I bet that should show the same problem, demonstrating it's not an issue in this library but either because something on your system is doing *stuff* with those files, or a bug in inotify.

- Verify fsnotify 1.6.0 still has this issue; it seems kubernetes updated their version in https://github.com/kubernetes/kubernetes/pull/113037, but dunno if that's in a release yet.

- The strace you posted earlier just contains the result from the Go compile process; run `go build` and then `strace program`.

---

And finally to @saurori, you're really seeing a different issue. I don't *think* that's a problem in fsnotify either, but you're using macOS with the kqueue backend which is significantly more complex than inotify (and also shares no code with it), so it certainly could be. As I mentioned before, I can't reproduce it though, either in my macOS VM, or in the CI, so I *suspect* it may also just be a process doing *stuff*, but hard to be sure. It might be the Spotlight indexing thing: https://github.com/fsnotify/fsnotify#macos – either way, open a new issue for it if you really think it's a problem in fsnotify and we can investigate further, rather than discussing two issues here.

**Comment by saurori** [comment] 2022-10-17 01:41
@arp242 Thanks for the thorough explanation. I did indeed conflate a bug I was seeing with the original issue mentioned here. But I was able t track it down in the library using `fsnotify` and help get it fixed: https://github.com/gobuffalo/refresh/issues/6

**Comment by cyclinder** [comment] 2022-10-19 02:52
Thanks, @arp242 👍

I think the root cause of this issue is not clear yet, it could be a kernel issue. But in Kubernetes, this can be avoided. So I proposed https://github.com/kubernetes/kubernetes/pull/107634 but the Kubernetes community didn't take it up, they thought it lacked sufficient testing.

So for kubernetes, I agree that more smarter handling of Chmod events is a better choice.

**Closed** 2022-10-30 11:00 UTC
Labels: bug, linux, help-wanted, need-feedback
