### ISSUE TITLE
.Close() does not always actually close all channels

### ISSUE THREAD

**Issue by mprobst** [fsnotify/fsnotify#132] opened 2016-04-08 08:48 UTC
It seems that `Watcher.Close` does not always cause its channels to close. Maybe when `Close()` happens, but fsnotify is currently reading events, it somehow doesn't terminate the read?

Roughly equivalent code to the stuff below reproduces the issue with a ~4% timeout rate for me:

``` go
func main() {
    w, err := fsnotify.NewWatcher()
    if err != nil {
        log.Exit(err)
    }
    // give some time for readEvents to start
    time.AfterFunc(time.Second, func() {
        log.Print("closing watcher")
        w.Close()
    })
    // give some time for readEvents to exit
    time.AfterFunc(10*time.Second, func() {
        log.Fatal("timeout")
    })
    // wait for channels to be closed
    c, errc := w.Events, w.Errors
    for c != nil || errc != nil {
        select {
        case e, ok := <-c:
            if !ok {
                log.Print("event channel closed")
                c = nil
                continue
            }
            log.Info(e)
        case err, ok := <-errc:
            if !ok {
                log.Print("error channel closed")
                errc = nil
                continue
            }
            log.Info(err)
        }
    }
}
```

**Comment by ppknap** [comment] 2016-04-08 10:36
Which OS do you use?

**Comment by mprobst** [comment] 2016-04-08 11:02
This is on Linux. Here's what another engineer wrote about this:

> This looks like a bug in fsnotify to me. I don't see anything in the Watcher's Close method that would interrupt its Read. The readEvents goroutine checks the done channel before the read, so if Close happens to signal done in time then readEvents will exit cleanly and close the Events and Errors channels. If the signal comes after the check, then it'll just hang unless a new event happens to make its way through and restart the loop.

This is a stack trace where fsnotify hangs:

```
goroutine 90 [syscall]:
syscall.Syscall(0x0, 0x9, 0xc8204bbe40, 0x10000, 0x0, 0x0, 0x0)
  third_party/go/gc/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x9, 0xc8204bbe40, 0x10000, 0x10000, 0x0, 0x0, 0x0)
  third_party/go/gc/src/syscall/zsyscall_linux_amd64.go:776 +0x5f
syscall.Read(0x9, 0xc8204bbe40, 0x10000, 0x10000, 0x0, 0x0, 0x0)
  third_party/go/gc/src/syscall/syscall_unix.go:161 +0x4d
third_party/golang/fsnotify/fsnotify.(*Watcher).readEvents(0xc82035e680)
  third_party/golang/fsnotify/inotify.go:144 +0x13f
created by third_party/golang/fsnotify/fsnotify.NewWatcher
  third_party/golang/fsnotify/inotify.go:47 +0x365
```

**Comment by ppknap** [comment] 2016-04-08 17:43
Are you sure that you have the latest version? It is quite obvious that fsnotify hangs on `syscall.Read` function which is currently [here](https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L205) (line 205). Your stack trace shows that the call to `syscall.Read` function is in line 144 which means that  you may use an old version of the package.

Honestly speaking, I don't believe that upgrading fsnotify will help(but it may). Implementation of `readEvents` function is definitely not thread safe..

**Comment by mprobst** [comment] 2016-04-08 18:53
I'm pretty sure I don't have the latest, but indeed the issue seems present
in the latest, too.

Pawel Knap <notifications@github.com> schrieb am Fr., 8. Apr. 2016, 19:43:

**Comment by ppknap** [comment] 2016-04-09 15:27
I cannot reproduce this bug on current master. Could you use version ^1.2.0 and confirm that this bug is still present?

**Comment by matthias-stone** [comment] 2018-08-30 20:59
Cannot reproduce now either, closing. If someone finds this again they should reopen or report a new issue.

**Closed by matthias-stone** 2018-08-30 20:59 UTC
Labels: Linux (inotify), bug
