### ISSUE TITLE
File/directory move

### ISSUE THREAD

**Issue by chmike** [fsnotify/fsnotify#170] opened 2016-09-27 15:15 UTC
Unfortunately fsnotify drops the cookie information provided with inotify on linux. As a consequence we loose the information on linked events. This is a problem for the move operation. 

When renaming a file in a monitored directory with the move operation as is mandatory in unix, we receive two events: 
1. a RENAME event with the old name
2. a CREATE event with the new name

When a file is moved out of the monitored directory we receive a simple RENAME event. 
So this API does not allow to distinguish from a move out and creation of a new file, and a rename operation. 

Trying to detect a file rename operation would be difficult because it requires to add a waiting time after a rename to detect a create. But this exposes to the possible confusion with a move out and an unrelated create following by coincidence.

The cookie provided with the inotify interface allows to detect interleaved events. This is not possible with the fsnotify interface. 

Testing directory rename/move operation is exposed to the same problem. When renaming a directory, inside a monitored directory, two events are generated like for a file rename.
But if I add a watcher for the new directory name (don't know if I have to remove the watcher for the old name) I get a rename event with the new name as argument.

If I remove a previous watcher when I receive the RENAME event, I then remove the watcher on the new name. When I rename the directory I get a fatal error with an error message that all go routines are sleeping. I have no idea what could cause this error. 

This is all inconsistent and confusing. 

I understand the attempt to have a simple and portable API, but this simply doesn't work as it should be. I also discover the inotify API of linux and this is a problem too. The cookie info is a hack. The need to add a wait for subsequent related events is very inconvenient. It introduces a latency in event handling and makes the code complex. 

If the event had two name arguments, that problem could have been avoided.

**Comment by bep** [comment] 2016-09-27 15:27
What is this issue about?

**Comment by chmike** [comment] 2016-09-27 16:27
Sorry, for the delayed update of the comment. The issue was posted by accident before I could fill the comment. I then double checked everything before posting the comment.

**Comment by chmike** [comment] 2016-09-28 10:12
The strength of fsnotify is the simplicity of its API. Unfortunately it lacks a good reporting of renaming/moving. 

The rename operation would require two names, the old and the new name. 
In order to add a good support of file renaming, could it be possible to add a second string field to the Event structure ? The string would be nil if the old or new name are not known.

**Comment by nathany** [comment] 2016-10-01 21:21
Renames and moves is certainly less than ideal in fsnotify -- not only with inotify, but across all operating systems. See also #26.

**Comment by arp242** [comment] 2022-07-30 14:33
Closing as duplicate of #26, as it contains essentially the same information.

**Closed by arp242** 2022-07-30 14:33 UTC
Labels: linux
