### ISSUE TITLE
Support Add with flag

### ISSUE THREAD

**Issue by tkan145** [fsnotify/fsnotify#436] opened 2022-03-08 00:59 UTC
**Is your feature request related to a problem? Please describe.**
A call to `Add`   will subscribe to all events, however, this is noisy when I need to watch multiple files. it would be great if we could call `Add` with flags. So if I just want to watch for CREATE event I can do so instead of parsing all of the necessary events

**Describe the solution you'd like**
`Add` do call `addWatch(name string, flags uint32) ` internally so this is more like just making this function public

```
// Add starts watching the named file or directory (non-recursively).
func (w *Watcher) Add(name string) error {
        return AddWithFlag(name, AllEvents)
}

func (w *Watcher) AddWithFlag(name string, flags uint32) error {
        .....
}
```

**Comment by arp242** [comment] 2022-07-22 05:59
Duplicate of #352

**Closed by arp242** 2022-07-22 05:59 UTC
Labels: proposal
