### ISSUE TITLE
Only one event is generate for mkdir -p a/b/c

### ISSUE THREAD

**Issue by yueqili** [fsnotify/fsnotify#32] opened 2014-08-16 10:45 UTC
mkdir -p a/b/c
I think it should generate one event with a/b/c
or 3 events for mkdir -p a/b/c

**Comment by markhuge** [comment] 2021-10-12 09:43
Running into similar issue detecting the initialization of new git repositories within a directory on a Linux host.

`git init foo` seems to `mkdir -p foo/.git`, so fsnotify never observes when a non-bare git repo is initialized within a watched dir.

**Comment by arp242** [comment] 2022-08-03 21:43
As mentioned, fsnotify is never recursive at the moment; hopefully that will be fixed *soon™* (e.g. sometime this year, but no promises). In the meanwhile, I'll close this as a duplicate of #18; you can follow that if you're interested in updates. I made a note to add a test case for this specific scenario in the work-in-progress branch I have to work on that (although I'm not yet entirely sure how well it can be made to work with all different backends).

**Closed by arp242** 2022-08-03 21:43 UTC
Labels: feature
