### ISSUE TITLE
Deadlock under high load

### ISSUE THREAD

**Issue by maja42** [fsnotify/fsnotify#215] opened 2017-08-13 14:33 UTC
This happens on windows, I haven't tested it on linux yet.
I use fsnotify to monitor a single directory ("parent") and all its direct subdirectories (no recursion).

I do this with 2 separate watchers: Watcher 1 monitors the parent directory, watcher 2 monitors all subdirectories.

- Everytime the parent-directory watcher tells me a new directory was created,
I add the new path to the subdirectory-watcher.

- Everytime the parent-directory watcher tells me a directory was deleted (or renamed, which is affectively the same), I remove the path from the subdirectory-watcher.

This works pretty well, usually. But then I created a script that creates, renames and removes folders pretty fast.
I have the following .bat script in the parent directory:

```
mkdir deleteThisDir1
rename deleteThisDir1 deleteThisDir2
rmdir deleteThisDir2
```

Calling this file once in a while is not a problem. But when I call this file in a loop, fsnotify eventually runs into a deadlock and does not emit any events anymore (less than 100 calls usually). If I call "watcher.Close()" after a few seconds, fsnotify shuts down cleanly.

This is my goroutine that receives events from fsnotify and aborts watching if the context is closed:

```
errOut := make(chan error)
go func() {
	defer func() {		
		if err := subdirWatcher.Close(); err != nil {
			errOut <- fmt.Errorf("Failed to close watcher: %s", err)
		}
		if err := parentWatcher.Close(); err != nil {
			errOut <- fmt.Errorf("Failed to close watcher: %s", err)
		}
		close(errOut)
	}()

	for {
		select {
		// parent watcher:
		case event := <-parentWatcher.Events:
			processParentEvent(event)
		case err := <-parentWatcher.Errors:
			errOut <- fmt.Errorf("Error while watching: %s", err)

		// sub directory watcher:
		case event := <-subdirWatcher.Events:
			processSubDirEvent(event)
		case err := <-subdirWatcher.Errors:
			errOut <- fmt.Errorf("Error while watching: %s", err)

		case <-time.After(2 * time.Second):
				log.Debug("No incoming events")
		// abort:
		case <-ctx.Done(): // context.Context
			return
		}
	}
}()
```

After a while, fsnotify deadlocks and emits no events (or errors) anymore; The log message, however, still logs every 2 seconds. When the context is canceled, everything is cleaned up successfully

**Comment by maja42** [comment] 2017-08-13 14:36
And yes, I use the version on the current master branch

**Comment by maja42** [comment] 2017-08-13 14:44
The already existing issue https://github.com/fsnotify/fsnotify/issues/164 might be a duplicate?
If I remove the "watcher.Remove(event.name)" call, like it was suggested in one of the comments there, the deadlock does not happen.

Maybe my .bat-script can help you to reproduce the issue? When I call it ~100 times, it happens nearly every time.

**Comment by arp242** [comment] 2022-08-10 23:21
I ran this a few times:

	@for /l %x in (1, 1, 10000) do (
		@mkdir deleteThisDir1
		@rename deleteThisDir1 deleteThisDir2
		@rmdir deleteThisDir2
	)

And it seems fine.

Your example code is only a part, and not something I can run, so I can't test it with that. You mention `watcher.Remove()`, but it's not in the example code(?)

I think this may have been fixed in the meanwhile; since this issue is five years old, I'll close it for now, but let me know if you can still reproduce it and we can investigate further.

**Closed by arp242** 2022-08-10 23:21 UTC
Labels: bug, windows
