### ISSUE TITLE
CLOSE_WRITE inotify event

### ISSUE THREAD

**Issue by valar999** [fsnotify/fsnotify#235] opened 2018-01-26 14:28 UTC
When file is changed, every write() call generate WRITE event. That is not what somebody usually want when waiting to file change. WRITE event can occur in partially written file, you get several write events, etc.

CLOSE_WRITE on the other hand occur when file actually changed (at least written) and close.
I think for inotify it is better to use CLOSE_WRITE instead of WRITE or make separate event for it.

**Comment by jaymell** [comment] 2018-02-07 17:05
I agree that it would be extremely useful to have CLOSE_WRITE available as a separate event type. Depending on WRITE events requires a lot of additional work to ensure that we aren't processing a file multiple times, or processing it before it's completely written.

**Comment by radu-munteanu** [comment] 2018-02-21 07:53
This issue was discussed a few times.

For GNU/Linux there are already a few forks doing just that (you can check mine if you like). The thing is this library was made to be cross-platform, you can't just add one new event if it has no use on all platforms.

**Comment by britishben** [comment] 2018-02-23 15:05
There's lots of related issues, so I think the devs are aware.

This is the one issue that stops me from dropping the old _inotify_ libraries for _fsnotify_, so I'm watching this with interest.

**Comment by jaymell** [comment] 2018-02-23 19:14
I totally understand the desire to add platform-specific features to a multi-platform library. But I also wonder, having no familiarity with the fsnotify code, if it's reasonable in certain situations to have event types that would just never be fired on certain platforms. We can all point to plenty of examples in various software libraries where common APIs nonetheless have platform-specific considerations associated with them.

**Comment by radu-munteanu** [comment] 2018-02-26 10:31
#191 #22 #173 #202

**Comment by matthias-stone** [comment] 2018-08-30 21:43
This is a duplicate of #191.

**Closed** 2018-08-30 21:44 UTC
Labels: API, Linux (inotify), feature, unplanned

**Comment by pablodz** [comment] 2022-06-03 21:40
please add close_write, it's extremelly useful

**Comment by pablodz** [comment] 2022-12-27 04:13
I built an alternative https://github.com/pablodz/inotifywaitgo
