### ISSUE TITLE
Edit notifications don't work when running inside of Docker container on Windows

### ISSUE THREAD

**Issue by matt-github-acct** [fsnotify/fsnotify#292] opened 2019-04-28 23:01 UTC
I'm running Windows 10 Enterprise, 10.0.17134

My goal is to launch a docker container, mount a volume inside the container, edit files in the volume from my host operating system and have the docker container recognize the change events. Pretty much this: https://www.zachjohnsondev.com/posts/go-docker-hot-reload-example/

*Steps to reproduce*
1. Create `main.go` file and add the following:
```
package main

import (
	"log"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Add(".")
	if err != nil {
		log.Fatal(err)
	}
	<-done
}

```
1. Create a `docker-compose` file and add the following:
```
version: "3.6"

services:
  bar:
    container_name: bar
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/bar
```
1. Create a `Dockerfile` file and add the following:
```
FROM golang:latest

WORKDIR /go/src/bar

COPY . .

RUN ["go", "get", "github.com/fsnotify/fsnotify"]

ENTRYPOINT go run main.go
```
1. Run `docker-compose build` in the directory where you've created the files.
1. Run `docker-compose up` in the directory where you've created the files.
1. From your host operating system, add a comment to `main.go` and notice that no edit events are reported.
1. Run `docker exec -it bar bash` to connect to the docker container. Edit `main.go` from the container shell to confirm that edit events are being reported when the edit is performed within the container.

**Comment by oxycoder** [comment] 2019-08-17 13:48
Same problem, any one have solutions?

**Comment by nathany** [comment] 2019-10-05 20:41
I'm not sure how Docker for Windows is mounting the shared folder, but generally file shares such as NFS don't support notifications.

A polling fallback (#9) is the only solution I know of when the underlying system doesn't provide events.

For now we should document the limitation, but first we should confirm on other operating systems. It may work on Linux, depending on how the Docker container is mounted there.

**Comment by oxycoder** [comment] 2019-10-06 02:25
Currently it work perfectly fine with folder mount to docker on MacOS.

**Comment by julienkosinski** [comment] 2019-11-15 14:33
I can confirm it works well under on Docker with Linux host (Manjaro distro)

**Comment by jnach** [comment] 2020-01-06 18:29
> I can confirm it works well under on Docker with Linux host (Manjaro distro).

Which storage driver do you happen to be using? With @nathany's comment in mind, this could be filesystem dependent. In both 'working' cases, this sounds like a bind mount, not a real storage driver under the PVC subsystem

**Comment by jnach** [comment] 2020-01-06 18:35
[This](https://william-yeh.net/post/2019/06/inotify-in-containers/) seems to do a good job of explaining the phenomenon here..

**Comment by jnach** [comment] 2020-01-06 18:39
> Same problem, any solutions?

Sorta, see above. TL&DR This is a file-system compatibility issue. There are a few scenarios where it works when using the _same underlying host filesystem_, but pretty much never if there is any translation.

**Comment by reyronald** [comment] 2020-05-20 15:39
I'm also interested in a workaround or solution to this, if there's any. Would be ok with polling if that does the job. Could be a CLI option

**Comment by Hanggi** [comment] 2020-09-25 02:44
Me too,

Is there any certain plan to cover this issue? 

There are several packages using fsnotify (eg: air, compileDaemon ...), 
I have tried them all, and these packages have the same issue, certainly.

**Comment by arp242** [comment] 2022-10-14 17:29
Closed as duplicate of #9; if the underlying OS mechanism doesn't work then there's not much we can do about it other than implement a polling fallback.

**Closed by arp242** 2022-10-14 17:29 UTC
Labels: documentation, help-wanted
