### ISSUE TITLE
Double firing of event

### ISSUE THREAD

**Issue by riccardomanfrin** [fsnotify/fsnotify#324] opened 2020-02-10 08:49 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

Linux: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

fsnotify version: ## v1.4.7 / 2018-01-09

### Please describe the issue that occurred.
Modifying a file either with 

     echo "helloworld" > /my/tmp/file

or by means of a generic editor (vim/nano/sublime) generates single or double OP 0x2 events on a random base (say 50% of the times I get single OP 0x2 events, and the other half I get the event twice).

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

Full code reference @ https://medium.com/@skdomino/watch-this-file-watching-in-go-5b5a247cf71f

This is the sensible part:

```
var watcher *fsnotify.Watcher

//Listen on file changes
func Listen() {
	defer watcher.Close()
	done := make(chan bool)

	go func() {
		for {
			select {
			// watch for events
			case event := <-watcher.Events:
				res, err := Read(&event.Name)
				if err != nil {
					continue
				}
				fmt.Printf("EVENT! %#v\n", event)
				logger.Log.Debug(*res)
				// watch for errors
			case err := <-watcher.Errors:
				logger.Fatal(err)
			}
		}
	}()

	<-done
}
```

**Comment by snowyyj001** [comment] 2020-02-18 07:44
I user the example code for test and it also trigger two times, it happened 100%.
if ev.Op&fsnotify.Write == fsnotify.Write {
//here will be called two times
}

**Comment by zhaocy** [comment] 2020-02-27 13:21
I had the same problem running the sample

**Comment by dmgcodevil** [comment] 2020-03-10 18:38
in my case, it fires 10+ events. mac os. go 1.13

**Comment by dkotik** [comment] 2020-03-20 17:23
Ubuntu 19.10 double firing for me as well.

**Comment by RiccardoManfrin** [comment] 2020-03-20 19:58
best  way to keep it under control is to md5sum compare changes

**Comment by chenqinghe** [comment] 2020-05-11 08:40
windows 10, go1.14  double firing too.

**Comment by ellis2323** [comment] 2020-06-02 15:27
windows 10 (version 2004), go1.14 double firing as well

**Comment by PaluMacil** [comment] 2020-08-08 01:13
same double READ result, Ubuntu 20.04

**Comment by sgon00** [comment] 2021-03-11 03:27
Debian 10 (MX Linux), Go 1.16.
I don't see double firing by using `echo` command when modifying the file. 
But I see double firing when using rich editors such as `vscode`.

Possible Related Issues:
https://github.com/fsnotify/fsnotify/issues/122
https://github.com/microsoft/vscode/issues/9419

**Comment by arp242** [comment] 2022-07-30 12:43
I'm closing this as a duplicate of #372; as mentioned in that issue, many editors don't "just" write a file, but will instead write it to a new file and then rename it.

Also, #470 should make things a little but more consistent, on Linux at least.

**Closed by arp242** 2022-07-30 12:43 UTC
Labels: linux, documentation
