### ISSUE TITLE
Watch stops receiving event after some time

### ISSUE THREAD

**Issue by VEDANTDOKANIA** [fsnotify/fsnotify#577] opened 2023-08-22 06:09 UTC
I faced an issue in the fs watcher . When my program runs for more than day or so , notifier stops working , and does not receive any events. Is there a timeout or something that i need to configure ? Also my goroutine is still running 

Code :- 

err = watcher.Add(utils.CurrentDir + utils.PathSeparator + utils.ConfigDir + utils.PathSeparator + "config.txt")

	if err != nil {

		serverLogger.Error(fmt.Sprintf("failed to initialize config watcher, reason: %v", err.Error()))
	}

	for {

		if utils.GlobalShutdown {

			return
		}

		select {

		case event := <-watcher.Events:

			if event.Op&fsnotify.Write == fsnotify.Write || event.Op&fsnotify.Rename == fsnotify.Rename {

				serverLogger.Info("config update request received...")

				bytes, err := os.ReadFile(utils.CurrentDir + utils.PathSeparator + utils.ConfigDir + utils.PathSeparator + utils.MotadataDataStoreConfigFile)

				if err == nil && len(bytes) > 0 {

					utils.ReloadConfigs(bytes)
				}
			}

		case err = <-watcher.Errors:

			serverLogger.Error(fmt.Sprintf("err %v occurred in config watcher", err.Error()))
		}
	}

**Comment by arp242** [comment] 2023-08-22 08:06
Please fill in the information requested in the issue template; it's there for a reason.

**Comment by arp242** [comment] 2023-10-17 19:16
Closing because there is not enough information here to reproduce the issue.

**Closed by arp242** 2023-10-17 19:16 UTC
Labels: need-feedback
