### ISSUE TITLE
GetPaths function to read out all watched paths.

### ISSUE THREAD

**Issue by chamabreu** [fsnotify/fsnotify#440] opened 2022-04-07 12:20 UTC
I need to get the paths, which are watched by the fsNotify.Watcher.
Because there is no `.removeAll()` function, I need to iterate over all watched Paths to then decide which Paths I want to remove.

A Solution like `.getAllWatchedPaths()` to get the `Path` map/array.

Target is, that I want to "Clear out" the Watcher, without closing and recreating it.
I need just One single Instance to work with, and want more possibilities to manipulate, like `.removeAll()` , `.getAllPaths()` , `.addMultiplePaths()` etc...

**Comment by arp242** [comment] 2022-07-21 14:39
What is your use case for this? If you added paths to a watcher, then it seems to me you already know which paths you're watching and can keep track of them for removal? Alternatively, you can close the watcher and create a new one to "clear" it (you mentioned you don't want to do that, but it's not clear to me why).

**Comment by arp242** [comment] 2022-07-21 16:01
Also: looks like there's an issue for this already: #93 So I'll close this as a duplicate of that one.

Still, it's important that people provide actual use cases. Otherwise it's not clear if a "list all watched paths" is even the best solution; maybe it is, or maybe there's a better solution to address the use case. So I would encourage you to still post it.

**Closed by arp242** 2022-07-21 16:01 UTC
Labels: insufficient

**Comment by chamabreu** [comment] 2022-07-21 16:05
Yes.
My usecase was solved with #374 

Thanks

**Comment by arp242** [comment] 2022-07-22 04:28
Oh right, I didn't realize that got added recently 🤦
