### ISSUE TITLE
File or directory changed

### ISSUE THREAD

**Issue by alexmeel** [fsnotify/fsnotify#154] opened 2016-07-06 00:38 UTC
Is there a way to know if it is a file or a directory that changed in Event.Name?

**Comment by nathany** [comment] 2016-07-06 17:55
Not currently. Some platforms include a flag for that but not all. Currently fsnotify is doing the lowest common denominator thing and not reporting it, as opposed to doing an os.Stat to always provide that information.

**Comment by arp242** [comment] 2022-08-03 22:51
Duplicate of #81

**Closed by arp242** 2022-08-03 22:51 UTC
Labels: feature
