### ISSUE TITLE
cannot find module providing package gopkg.in/fsnotify/fsnotify.v1

### ISSUE THREAD

**Issue by publicocean0** [fsnotify/fsnotify#331] opened 2020-04-15 15:36 UTC
Linux: ubuntu 18
go get github.com/revel/cmd/revel
go: found github.com/revel/cmd/revel in github.com/revel/cmd v0.21.1
go: finding module for package github.com/jessevdk/go-flags
go: finding module for package github.com/agtorre/gocolorize
go: finding module for package github.com/revel/log15
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
go: finding module for package github.com/revel/config
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/mattn/go-colorable
go: finding module for package gopkg.in/stack.v0
go: finding module for package gopkg.in/natefinch/lumberjack.v2
go: found github.com/agtorre/gocolorize in github.com/agtorre/gocolorize v1.0.0
go: found github.com/jessevdk/go-flags in github.com/jessevdk/go-flags v1.4.0
go: found github.com/mattn/go-colorable in github.com/mattn/go-colorable v0.1.6
go: found github.com/revel/config in github.com/revel/config v0.21.0
go: found github.com/revel/log15 in github.com/revel/log15 v2.11.20+incompatible
go: found gopkg.in/natefinch/lumberjack.v2 in gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: found gopkg.in/stack.v0 in gopkg.in/stack.v0 v0.0.0-20141108040640-9b43fcefddd0
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
go: finding module for package github.com/inconshreveable/log15/term
go: found github.com/inconshreveable/log15/term in github.com/inconshreveable/log15 v0.0.0-20200109203555-b30bc20e4fd1
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
pkg/mod/github.com/revel/cmd@v0.21.1/watcher/watcher.go:15:2: cannot find module providing package gopkg.in/fsnotify/fsnotify.v1: module gopkg.in/fsnotify/fsnotify.v1: reading http://sr-vm318-kubert.comune.intranet:3000/gopkg.in/fsnotify/fsnotify.v1/@v/list: 404 Not Found

**Comment by notzippy** [comment] 2020-04-26 06:15
This basically means you should not import it in that format anymore. The added go.mod file to the root causes the error
```
go: gopkg.in/fsnotify/fsnotify.v1@v1.4.9: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.4.9
```
Similar issue, solution was to change the import method

**Comment by christophberger** [comment] 2020-06-03 06:45
Was the import path intentionally changed from gopgk.in to github.com, or does go.mod contain a wrong import path? The latter can be fixed by changing the first line to
```
module "gopkg.in/fsnotify.v1"
```

(example: [go-yaml/yaml's go.mod](https://github.com/go-yaml/yaml/blob/v2/go.mod))

**Comment by AlekSi** [comment] 2021-01-30 10:22
See https://github.com/go-fsnotify/fsnotify

**Comment by JimFran** [comment] 2022-06-28 08:01
Getting this message when importing "github.com/fsnotify/fsnotify"
"
```
could not import github.com/fsnotify/fsnotify (cannot find package "github.com/fsnotify/fsnotify" in any of 
	/usr/local/Cellar/go/1.18.1/libexec/src/github.com/fsnotify/fsnotify (from $GOROOT)
	/Users/username/go/src/github.com/fsnotify/fsnotify (from $GOPATH))compiler[BrokenImport](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#BrokenImport)
```

Any idea?

**Comment by arp242** [comment] 2022-07-24 11:31
Closing due to lack of feedback from the issue author.

**Closed by arp242** 2022-07-24 11:31 UTC
