### ISSUE TITLE
Looking forward to file opening events in Windows system

### ISSUE THREAD

**Issue by fengfengzhidao** [fsnotify/fsnotify#643] opened 2024-08-01 03:20 UTC
Hello, I want to implement the event behavior of opening directories and files in Windows

Under Linux, this is feasible, but on Windows systems, it seems less feasible

Is there any solution

Under Linux system, it is okay

![image](https://github.com/user-attachments/assets/1e455995-457a-4d01-9509-44209bdcab12)

**Comment by arp242** [comment] 2024-08-02 00:59
I don't think Windows supports this, at least not according to my table here: https://github.com/fsnotify/fsnotify/issues/519#issuecomment-2081575632

Maybe CHANGE_LAST_ACCESS can be used for this? I don't know. Getting the behaviour to be consistent might be tricky. OpenBSD and FEN also don't support it (although in FEN, FILE_ACCESS can perhaps be used).

**Comment by arp242** [comment] 2024-10-28 10:00
Closing as dupe of aforementioned issue.

**Closed by arp242** 2024-10-28 10:00 UTC
