### ISSUE TITLE
Is it mandatory to remove the file watcher when the file removed in Linux(Ubuntu)

### ISSUE THREAD

**Issue by jiangytcn** [fsnotify/fsnotify#168] opened 2016-09-20 09:21 UTC
Just as the title. Is it necessary to manually remove the file watcher when the REMOVE action occurred ? or the watcher still hold the file descriptor even the file doesn't exist any more ?

**Comment by nathany** [comment] 2016-10-01 21:46
When I first started using fsnotify I had the same question and wrote all the code to remove the watchers only to find that the remove failed because the watch was already gone. I was using kqueue on macOS at the time, so I'm not 100% sure for inotify on Linux.

**Comment by nathany** [comment] 2016-10-04 20:14
Documenting that it's unnecessary would be good -- though it would be good if it handled removing better as well.

**Comment by arp242** [comment] 2022-07-30 12:33
Closing this as a duplicate of #238, as it's essentially the same issue.

**Closed by arp242** 2022-07-30 12:33 UTC
Labels: linux, documentation, help-wanted
