### ISSUE TITLE
received duplicated events on MacOS

### ISSUE THREAD

**Issue by figo** [fsnotify/fsnotify#251] opened 2018-06-12 23:52 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1314

### Please describe the issue that occurred.

- Watch a directory,

- Create a file1 under directory; receive events: 

      file1 CREATE

- Create a file2 under directory; receive event:

      file1 CREATE
      file2 CREATE

- Create a file3 under directory; receive events:

      file1 CREATE
      file2 CREATE
      file3 CREATE

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.
yes, it happen everytime on macos

**Comment by liov** [comment] 2019-12-24 09:48
windows same as

**Comment by arp242** [comment] 2022-07-31 21:02
I am not able to reproduce this; I get:

	[~/fsnotify]% go run ./cmd/fsnotify test
	23:76:34.0357 watching; press ^C to exit
	23:76:43.4215   1 CREATE                "test/file1"
	23:76:50.2822   2 CREATE                "test/file2"
	23:76:54.9195   3 CREATE                "test/file3"

With the commands:

	[~/fsnotify/test]% touch file1
	[~/fsnotify/test]% touch file2
	[~/fsnotify/test]% touch file3

I would expect more people to report this if it's a wide-spread issue, too.

I'll close this for now as it's an older issue with no clear steps to reproduce, but we can reopen if more details are added.

**Closed by arp242** 2022-07-31 21:02 UTC
Labels: bug, macOS
