### ISSUE TITLE
can fsnotify watch file change for more than one time?

### ISSUE THREAD

**Issue by Jam-Lin** [fsnotify/fsnotify#94] opened 2015-09-08 07:47 UTC
i find fsnotify can only watch file change for one time. when i change the file twice. the watcher.Event chan is close, so i can not get the change event.

**Comment by nathany** [comment] 2015-10-13 03:13
If you are watching an individual file and it moves, it may no longer be being watched. Better to watch the directory the file is in.

If you believe there is a bug, can you please provide more details, such as operating system you are using and a code snippet to reproduce the issue? Thanks.

(sorry for the late reply)

**Comment by kkirsche** [comment] 2016-10-04 18:31
I'm experiencing similar behavior to this:

```
~/g/g/s/g/k/notify-git ❯❯❯ notify-git -v -p 45b9b05b0ff8732e70ccea9a30b0eaedd038c9c0
DEBU[0000] Git repository path: /Users/v832272/git/test
DEBU[0000] File to be monitored: rr1.txt
DEBU[0000] Waiting in goroutine...
DEBU[0005] Event received.                               event="/Users/v832272/git/test/rr1.txt": RENAME
DEBU[0005] Message sent to action
```

I'd expect the goroutine to receive a second event:

    go func(commitNeeded chan time.Time) {
			for {
				logrus.Debugln("Waiting in goroutine...")
				select {
				case event := <-watcher.Events:
					logrus.WithField("event", event).Debugln("Event received.")
					changedTime := time.Now()
					commitNeeded <- changedTime
					logrus.Debugln("Message sent")
				case caseErr := <-watcher.Errors:
					logrus.WithError(caseErr).Errorln("Received error from file watcher.")
				}
			}
		}(commitNeeded)

**Comment by nathany** [comment] 2016-10-04 19:05
@kkirsche sorry, I'm not sure I follow what's happening in your example.

moving/renaming doesn't work so well with the underlying OS notification systems #26

btw, which operating system are you testing on?

**Comment by kkirsche** [comment] 2016-10-04 19:08
Vim write events on MacOS trigger as Move / Rename @nathany 

e.g. vim /path/to/file.txt

Make an edit, then :wq results in that type of event

**Comment by kkirsche** [comment] 2016-10-04 19:10
@nathany 

OS: OS X El Capitan
Moving / Renaming seems to be the only type of event I can get to trigger. Vim triggers it, textedit triggers it. Is there anyway to actually hook into more "normal" use cases to watch the file?

**Comment by kkirsche** [comment] 2016-10-04 19:16
Hm, apparently it was cause I was triggering off of any event rather than just watches. I got it fixed with the example_test.go code, but it wasn't clear.

**Comment by nathany** [comment] 2016-10-04 19:41
@kkirsche Do you have any suggestions for improving the example code or documentation?

**Comment by kkirsche** [comment] 2016-10-04 19:51
For me, the biggest issue was that I'm running this as a longer running daemon, so cleanup was something that was a problem. It seemed as though I was leaving the watcher active (`gocode` process on OS X) which needed to have the following:

```
c := make(chan os.Signal, 1)
signal.Notify(c, os.Interrupt)
go func() {
	for _ = range c {
		fmt.Println("")
		logrus.Infoln("Cleaning up...")
		doneWatch <- true
		done <- true
	}
}()
```

This then sent the messages to close the watcher and close any open channels. Once I added that, I didn't run into any more gocode running after ctrl+c ended the application running.

The second thing for me which was unclear from the example was what the purpose of the done channel was since it was a bit too simplistic for me to really be able to use as a template to really base my code on. I made a more generic version to show what I was using the watch event for if it helps understand the situation.

https://github.com/kkirsche/notify-git/blob/master/cmd/root.go

Lastly, I had to exit the goroutine on the above done event, or else the watcher would catch a ton (near infinite it seemed) <nil> errors / "" events. For this reason I'd have the done channel also exit the background goroutine in case they do any debug messaging to avoid flooding stdout. 

I guess my takeaways were that it would be nice to include cleanup code in the example, and provide a more "complete" implementation that leverages the done channel.

Does that help?

**Comment by tscott0** [comment] 2017-03-17 19:59
> Potentially it'd also be helpful to have a wiki page of known programs that don't trigger write events to avoid the "hm, why doesn't vim editing the file work?"

@nathany, I was also using vim to test and it wasn't working. I would instead see RENAME, CHMOD, REMOVE events. It would be great to perhaps have a list of known applications that perhaps don't interract with fsnotify as you might expect, this could become a FAQ page or similar.

Examples of how you might trigger specific events might be useful. While these may seem obvious and would be platform-specific, it would be great to show what happens when you chmod, touch, append and delete (rm) a file from the command line.

**Comment by Shashankft9** [comment] 2021-03-08 17:14
Hey I am also facing the same issue, if anyone could help with any resolutions for this? 
@kkirsche can you please highlight in your example, which part helped you in receiving the second event as well? Is this somehow related to the cleanup you are doing?

**Comment by ArpithaRao** [comment] 2021-09-14 21:13
Hello, with fsnotify new watcher for a single file, the event is triggered only when the file is copied from elsewhere to the interested directory, for file thats moved or edited its not working. Is this expected? Are there any resolutions for these?

**Closed** 2022-08-10 15:10 UTC
Labels: documentation, help-wanted
