### ISSUE TITLE
macOS: No events fired when watching os.TempDir

### ISSUE THREAD

**Issue by aeneasr** [fsnotify/fsnotify#340] opened 2020-05-14 18:48 UTC
# Which operating system (GOOS) and version are you using?

```
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

% go version
go version go1.14.2 darwin/amd64

% cat go.sum | grep fsnotify
github.com/fsnotify/fsnotify v1.4.9 h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=
github.com/fsnotify/fsnotify v1.4.9/go.mod h1:znqG4EE+3YCdAaPaxE2ZRY/06pZUdp0tY4IgpuI1SZQ=
```

### Please describe the issue that occurred.

Files created directly in `os.TempDir` do not trigger `WRITE` events.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

Take the following Go program

```go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/fsnotify/fsnotify"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	watcher, err := fsnotify.NewWatcher()
	check(err)

	toWatch := filepath.Dir(os.TempDir())
	watcher.Add(toWatch)

	fmt.Println("watching dir: ", toWatch)
	for {
		select {
		case event, ok := <-watcher.Events:
			fmt.Println(ok, event.String())
		case err, ok := <-watcher.Errors:
			fmt.Println(ok, err)
		}
	}
}
```

and run it. The output is along the lines of:

```
% go run main.go
created file:  /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/config-577573451.yaml
watching dir:  /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T
```

Now open another terminal and do:

```
% echo bar > /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/config-577573451.yaml
% echo bar > /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/another-file.yml
% mkdir /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/another-dir
```

No events will be fired despite the file having changed. I don't think it's a permission thing:

```
 % ls -la /var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/ 
total 24
drwxr-xr-x@   6 mainuser  staff    192  3 Jan 17:20 .
drwxr-xr-x@   3 root    wheel     96 12 Mai  2019 ..
-rw-r--r--@   1 mainuser  staff   8196  4 Jan 12:44 .DS_Store
drwxr-xr-x@  19 mainuser  staff    608 29 Mär 12:28 0
drwx------@ 339 mainuser  staff  10848 14 Mai 14:34 C
drwx------@  91 mainuser  staff   2912 14 Mai 20:42 T
```

Any other directory seems to be working fine. Subdirectories of `os.Temp` also work fine. It also works fine if I watch a specific file (for modifications on the file).

Sometimes I do however see events firing - these file changes come from the IDEs or other places:

```
true "/var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/TemporaryItems": CREATE
true "/var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/.keystoneAgentLock": CHMOD
true "/var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T/.keystoneAgentLock": CHMOD
```

Kind of feel like going insane, having checked the dirnames probably hundreds of times. However, I originally found this because a test case was failing on macOS but working fine on our CI which runs Linux.

**Comment by arp242** [comment] 2022-07-31 01:05
I tested this on macOS 12, and it seems to work; events get generated:

    % go run ./cmd/fsnotify $TMPDIR
	02:76:13.7602 watching; press ^C to exit
	02:76:32.8585   1 CREATE                "/var/folders/01/5qf4m0jn7rz_15kt2fm5p6g40000gn/T/asd"
	02:76:48.3085   2 WRITE      (modified) "/var/folders/01/5qf4m0jn7rz_15kt2fm5p6g40000gn/T/asd"

For the commands:

	% touch $TMPDIR/asd
	% print asd>> $TMPDIR/asd

Tried a bunch of other commands and repeated it a few times; and it all seems fine as far as I can see.

---

Note that your code does have:

	toWatch := filepath.Dir(os.TempDir())
	watcher.Add(toWatch)

So you may be watching the wrong directory? On my system $TMPDIR ends with a `/` so it works, but maybe that's not the case on your system?

	% print $TMPDIR
	/var/folders/01/5qf4m0jn7rz_15kt2fm5p6g40000gn/T/

You're also using both `var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/T` *and* `/var/folders/lp/y6b0bzs17svbmbl4fmr9h1z40000gn/` (without the last `/T/` part), so maybe some pathnames got mixed up?

---

I'm closing this for now because I can't reproduce, but get back to me if you're still having this issue and we can reopen and look furher.

**Closed by arp242** 2022-07-31 01:05 UTC
Labels: bug
