### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by jiangytcn** [fsnotify/fsnotify#164] opened 2016-09-04 06:09 UTC
Is it a bug or something?
After one week or so , my program stop running, only left the exceptions below.
What i want to do is wathcing the changes of the base directory, and if theres sub directory creation event occuied, then add it to the watcher. 

```
fatal error: concurrent map read and map write
goroutine 6 [running]:
runtime.throw(0xab67e0, 0x21)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820195d18 sp=0xc820195d00
runtime.mapaccess1_fast64(0x8b2960, 0xc82000fad0, 0x1, 0xc820195d98)
        /usr/local/go/src/runtime/hashmap_fast.go:112 +0x5a fp=0xc820195d38 sp=0xc820195d18
github.com/XXXXXXXX/gosync/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc820018aa0)
        /home/ubuntu/go/src/github.com/XXXXXXXX/gosync/vendor/github.com/fsnotify/fsnotify/inotify.go:253 +0x6bf fp=0xc8201a5f58 sp=0xc820195d38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201a5f60 sp=0xc8201a5f58
created by github.com/XXXXXXXX/gosync/vendor/github.com/fsnotify/fsnotify.NewWatcher
        /home/ubuntu/go/src/github.com/XXXXXXXX/gosync/vendor/github.com/fsnotify/fsnotify/inotify.go:61 +0x3e2
```

**Comment by nathany** [comment] 2016-09-08 15:29
Thanks for the report @jiangytcn.

We are running the tests with `-race` yet it hasn't caught this issue. From your description, it sounds like it rarely occurs, which is going to make it hard to track down.

Please let us known what `go version` you are using and if possible, include some sample code for how you are using fsnotify. Thanks.

**Comment by oozie** [comment] 2016-09-14 00:44
@jiangytcn 

Is it possible that somewhere in your consuming code you instantiate a watcher, and assign it to a field on a struct by value, as opposed to a reference? In such case more than one mutexes are created to guard the same set of maps.

**Comment by oozie** [comment] 2016-09-14 21:46
Let me illustrate what I mean with code. The following snippet will fail pretty reliably:
```
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path"
	"strconv"
	"time"

	"github.com/fsnotify/fsnotify"
)

type Test struct {
	Watcher fsnotify.Watcher
}

func main() {

	testDirPrefix := "/tmp/test"

	w, _ := fsnotify.NewWatcher()
	t := Test{Watcher: *w}

	fmt.Println("creating test dir")

	concDirs := 100
	fmt.Println("adding watchers...")
	for i := 0; i < concDirs; i++ {
		dirName := path.Join(testDirPrefix, strconv.Itoa(i))
		os.MkdirAll(dirName, 0700)
		t.Watcher.Add(dirName)
	}

	go func() {
		fmt.Println("polling...")
		for {
			select {
			case <-t.Watcher.Events:
			}
		}
	}()

	time.Sleep(time.Second)

	for i := 0; i < concDirs; i++ {
		dirName := path.Join(testDirPrefix, strconv.Itoa(i))
		os.MkdirAll(dirName+"/subdir", 700)
		go func() {
			for {
				t.Watcher.Add(dirName + "/subdir")
				ioutil.WriteFile(path.Join(dirName, "file"), []byte("blah"), 0600)
				t.Watcher.Remove(dirName + "/subdir")
			}
		}()
	}

	time.Sleep(time.Second)

	fmt.Println("cleaning up")
	time.Sleep(1 * time.Second)
	os.RemoveAll(testDirPrefix)
}
```
until the following patch is applied
```
diff --git a/example.go b/example-fix.go
index f9ccfc0..f555803 100644
--- a/example.go
+++ b/example-fix.go
@@ -12,7 +12,7 @@ import (
 )

 type Test struct {
-	Watcher fsnotify.Watcher
+	Watcher *fsnotify.Watcher
 }

 func main() {
@@ -20,7 +20,7 @@ func main() {
 	testDirPrefix := "/tmp/test"

 	w, _ := fsnotify.NewWatcher()
-	t := Test{Watcher: *w}
+	t := Test{Watcher: w}

 	fmt.Println("creating test dir")

```
Pretty subtle.

**Comment by oozie** [comment] 2016-09-14 22:28
The larger issue can probably be addressed this way (I might be missing something though):
```
diff --git a/inotify.go b/inotify.go
index 9700df5..44f3aa6 100644
--- a/inotify.go
+++ b/inotify.go
@@ -23,8 +23,8 @@ import (
 type Watcher struct {
  Events   chan Event
  Errors   chan error
- mu       sync.Mutex // Map access
- cv       *sync.Cond // sync removing on rm_watch with IN_IGNORE
+ mu       *sync.Mutex // Map access
+ cv       *sync.Cond  // sync removing on rm_watch with IN_IGNORE
  fd       int
  poller   *fdPoller
  watches  map[string]*watch // Map of inotify watches (key: path)
@@ -55,8 +55,9 @@ func NewWatcher() (*Watcher, error) {
    Errors:   make(chan error),
    done:     make(chan struct{}),
    doneResp: make(chan struct{}),
+   mu:       &sync.Mutex{},
  }
- w.cv = sync.NewCond(&w.mu)
+ w.cv = sync.NewCond(w.mu)

  go w.readEvents()
  return w, nil
```
But it would require some more extensive testing. What do you guys think about this solution?

**Comment by jiangytcn** [comment] 2016-09-20 09:00
Sorry for the late response :), for the issue i reported, after removed the `watcher.Remove(event.Name) ` function call, the issue resolved. I don't know whether its a good resolution to it. But for now i met another issue about the scripts still hold the file descriptors, `lsof +L1`  shows a lot of deleted file still occupied by the program, need to manually restart the program

**Comment by nathany** [comment] 2016-10-01 22:02
Thanks @oozie and @jiangytcn. Related to #168.

**Comment by maja42** [comment] 2017-08-13 14:45
I have a similar issue (reproducable) that might be caused by the same issue (at least the workaround of not removing the watcher worked for me too): https://github.com/fsnotify/fsnotify/issues/215

**Comment by arp242** [comment] 2022-08-03 09:26
The line:

	github.com/fsnotify/fsnotify/inotify.go:253

Corresponds to this in `readEvents()` in v1.3.1:

	w.mu.Lock()
	name := w.paths[int(raw.Wd)]
	w.mu.Unlock()

So it *is* locked, but it looks like you're derefencing the pointer per oozie's example?

Basically, don't do that 🙃 But I created #482 to fix it.

**Comment by shogo82148** [comment] 2022-08-04 12:56
It is not a bug.
We must use `*fsnotify.Watcher` instead of `fsnotify.Watcher`.
There is no guarantee that the copied `Watcher` will work properly.
Please run `go vet` to find incorrect use of `fsnotify.Watcher`.

see also: https://github.com/fsnotify/fsnotify/pull/482#issuecomment-1205214379

**Closed** 2022-08-04 13:00 UTC
Labels: bug, linux
