### ISSUE TITLE
File Notification not working in NFS storage

### ISSUE THREAD

**Issue by weiyuefei** [fsnotify/fsnotify#306] opened 2019-09-24 07:18 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

### Please describe the issue that occurred.
We have 2 NFS clients, saying that A and B, and A and B have a share mount point /opt/files. We deploy our app which integrates fsnotify on A, another app writes data to /opt/files on B. We were surprised to find that the app could not catch the events when files were written on B. 
  
### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.
1. deploy one NFS server and two NFS clients.
2. add some share path on one of NFS clients, and write data to the share path on the other NFS client.

**Comment by nathany** [comment] 2019-10-05 16:09
This is a limitation of the underlying file watcher (inotify) and all watchers on other operating systems as far as I am aware.

This should be documented in the FAQ section fo the README.

We don't currently have a polling fallback (see #9) for use cases like this.

**Comment by Pratik32** [comment] 2019-10-07 05:18
@nathany , I think same is applicable for FUSE too. FUSE kernel module does not support notification for metadata changes. 
For NFS I  suggest we can do following:
1) A dedicated worker thread that caters remote fsnotify requests. (since the notify events will always be visible on sever where filesystem is actually mounted.)

**Comment by arp242** [comment] 2022-07-24 11:39
As mentioned inotify does not work over NFS; I'm closing this as a duplicate of #9.

Another solution would be to run a daemon on the NFS server which monitors events, and then your NFS client connects to that and read events from that. But I think that's out-of-scope for this library, although if someone creates a new `fsnotifyd` project or some such we can add it to the organisation.

**Closed by arp242** 2022-07-24 11:39 UTC
Labels: Linux (inotify), documentation, help-wanted, hacktoberfest
