### ISSUE TITLE
Symlink regression in v1.5.0

### ISSUE THREAD

**Issue by bep** [fsnotify/fsnotify#390] opened 2021-08-23 16:22 UTC
See https://github.com/gohugoio/hugo/issues/8920

On Linux.
 
/cc @pamubay

**Comment by nathany** [comment] 2021-08-23 16:25
Thanks for the report.

@Code0x58 Are you willing to look into this?

**Comment by nathany** [comment] 2021-08-24 17:55
There appear to be quite a number of regressions in v1.5.0 in addition to this one: #393 #389.

Thinking we may need to rollback the changes for now -- so we can take our time on giving it another try.

/cc @Code0x58 @nshalman

**Comment by nshalman** [comment] 2021-08-24 18:38
> Thinking we may need to rollback the changes for now -- so we can take our time on giving it another try.
I support that.

**Comment by nathany** [comment] 2021-08-24 19:40
v1.5.1 reverts the changes from 1.5.0, but lets leave this open to review.

**Comment by mterwill** [comment] 2022-08-19 14:57
👋 any plans to revisit adding support for watching symlinks without following? Thanks!

**Comment by arp242** [comment] 2022-10-13 05:24
> any plans to revisit adding support for watching symlinks without following? Thanks!

This can't be easily changed without breaking compatibility. The current situation is unfortunate because the behaviour is inconsistent on different platforms, but clearly people rely on it so it can't "just" be changed. The current API also doesn't give us much room for adding options to Add() or some such, so idk...

Either way, this is a duplicate of #227, so closing it.

**Closed by arp242** 2022-10-13 05:24 UTC
Labels: bug, linux
