### ISSUE TITLE
Mounted (shared via VMware) drives never seem to trigger events

### ISSUE THREAD

**Issue by matryer** [fsnotify/fsnotify#90] opened 2015-08-31 16:14 UTC
Directories in `/mnt/hgfs/...` never trigger anything.

This kind of makes sense since they're not really part of the same system, but I wonder if the package could notice this and use polling instead?

Worst case, we should probably just document this.

Alternatively, an option to always poll regardless of OS might also work.

**Comment by omeid** [comment] 2015-09-01 00:28
-1 for always polling.

This problem can be solved in multiple ways once the _driver-based_ based design disccuesed in #8 progresses.

**Comment by nathany** [comment] 2015-09-01 00:56
Revert to polling #9 or report an error like #45.

**Comment by omeid** [comment] 2015-09-01 01:03
@nathany Any plans for fsnotify dirver-based architecture change?

**Comment by nathany** [comment] 2015-09-01 15:30
@omeid Not as of yet. See https://github.com/go-fsnotify/fsnotify/milestones

**Comment by arp242** [comment] 2022-07-24 11:42
Closing as duplicate of #9.

**Closed by arp242** 2022-07-24 11:42 UTC
Labels: documentation, help-wanted, hacktoberfest
