### ISSUE TITLE
Modifying a file using vi causes a "Rename" event instead of a "Write" event

### ISSUE THREAD

**Issue by ahrtr** [fsnotify/fsnotify#282] opened 2019-02-12 08:07 UTC
Environment: 

> ProductName:	Mac OS X
> ProductVersion:	10.13.4
> BuildVersion:	17E202
>go version:            go 1.11 darwin/amd64

When I modify a file using vi on Mac OS X, the fsnotify generates a "Rename" event instead of a "Write" event. Note that this issue can only be reproduced on Mac OS X.

**Comment by benitogf** [comment] 2019-02-12 10:45
known issue, there's a lot of discussion about it already, https://github.com/fsnotify/fsnotify/issues/26

**Comment by bep** [comment] 2019-02-12 14:11
>When I modify a file using vi on Mac OS X

This depends on the editor used. Some editors do atomic saves that trigger a rename, so I'm not sure `fsnotify` is doing something wrong here.

**Comment by benitogf** [comment] 2019-02-12 14:17
@bep true, I found that [disabling the swap](https://stackoverflow.com/questions/821902/disabling-swap-files-creation-in-vim) files will help, but re-watching the file is more environment friendly imho

**Comment by ahrtr** [comment] 2019-02-12 14:25
Actually there are two issues:
1. Just as I mentioned above, a "Rename" event instead of a "Write" event is generated when modifying  a file using vi directly;

2. The second issue is related to the first issue. When fsnotify receives a false "Rename" event, it will remove the file from the watch list. Accordingly it will never receive any events of the file any more.

**Comment by radu-munteanu** [comment] 2019-02-22 09:16
I just came to say I am tired of people asking the same things over and over without reading the issues and comments already posted. It's like they don't want to learn anything or accept you can be wrong. When I started using fsnotify, I had no clue how it works, but I've started to do some tests first with inotify tool on GNU/Linux, looking for the messages generated by different apps doing different actions on files. Then, I've start writing some code that includes this lib to see how it all works out. It all made sense.

If you don't know how your editor works, or how file system notification works in general, just stop saying nonesense, especially after others have told you it's the correct behaviour. There is no "fake" rename and no "issue" with the library. It's a lower level lib than you think it is and you should put your lazy arse to work and write some code on top of it.

**Comment by benitogf** [comment] 2019-02-23 10:25
@radu-munteanu please be kind, questions are opportunities to incite curiosity  🍵

**Comment by radu-munteanu** [comment] 2019-02-25 08:34
@jazzdan @benitogf I wrote a long post but deleted everything... it's just another year of people getting offended by anything, even if it's the truth.

This issue relates to #17, #214, #254, #255, #279.

 @nathany Good luck managing this repo. I'm not going to give any inputs on anything.

**Comment by Alex1990** [comment] 2019-04-14 17:07
Maybe, it is efficient to note about it in the GoDoc page. So, someone confused doesn't need to search the issues, and you don't need to answer it over and over again.

**Comment by arp242** [comment] 2022-07-29 20:57
I'm closing this as a duplicate of #372; that issue is newer, but more comprehensive.

**Closed by arp242** 2022-07-29 20:57 UTC
