### ISSUE TITLE
I want to use ReadDirectoryChanges to watch subtree on windows. Do you have any ideas?

### ISSUE THREAD

**Issue by mstmdev** [fsnotify/fsnotify#397] opened 2021-09-10 08:59 UTC
https://github.com/fsnotify/fsnotify/blob/466b39d216616549a37ee93c7c47775f6a010790/windows.go#L351-L352

Because when I add all of sub dir to `Watcher`, and try to remove the parent dir, it asked me for an administrators role.
So I try to changed `ReadDirectoryChanges`'s `watchSubTree` by true, then it worked.

**Comment by arp242** [comment] 2022-07-30 13:11
This isn't supported yet; there's an open PR for it (#339), but it needs a bit more work. 

It should (hopefully) be in the next release, but for now, you can use that PR with a `replace` directive in your go.mod if you want.

Closing as a duplicate of #21.

**Closed by arp242** 2022-07-30 13:11 UTC
Labels: windows, feature
