### ISSUE TITLE
Watcher.Close panics on racing Close's due to double closing the done chan

### ISSUE THREAD

**Issue by thediveo** [fsnotify/fsnotify#456] opened 2022-06-08 12:07 UTC
Before reporting an issue, please ensure you are using the latest release of `fsnotify`, and please
search for existing issue to avoid duplicates.

**Describe the bug**

`Watcher.Close()` (as of today's master) currently does not protect the critical section of closing a watcher's internal `done` channel against racing `Close` calls here: https://github.com/fsnotify/fsnotify/blob/0f4b979323bea7ee6677faa4a88078ec558b1b80/inotify.go#L80. It can panic under racing Close calls due to the channel getting closed more than once, due to the ineffective guard using `w.isClosed` not being in a guarded critical section with its corresponding `close`. When two goroutines happen to be scheduled on racing OS threads and CPU cores they can pass the `isClosed` check at nearly the same time and then one of the racing threads/goroutine will attempt to close and already closed channel, triggering a runtime panic.

**Comment by arp242** [comment] 2022-07-21 14:56
This is a duplicate of #367, so I'll close this one (I confirmed the bug exists; I'll get it fixed some time this week).

**Closed by arp242** 2022-07-21 14:56 UTC
