### ISSUE TITLE
"Write" op never reported on Ubuntu.

### ISSUE THREAD

**Issue by dradtke** [fsnotify/fsnotify#92] opened 2015-09-02 20:12 UTC
I've tested this program on two flavors of Linux, openSUSE 13.2 and Ubuntu 14.04:

``` go
package main

import (
    "fmt"
    "gopkg.in/fsnotify.v1"
)

func main() {
    watcher, err := fsnotify.NewWatcher()
    if err != nil {
        panic(err)
    }
    watcher.Add("hello.txt")
    defer watcher.Close()

    for {
        select {
        case event := <-watcher.Events:
            if event.Op&fsnotify.Create == fsnotify.Create {
                fmt.Println("CREATE " + event.Name)
            } else if event.Op&fsnotify.Write == fsnotify.Write {
                fmt.Println(" WRITE " + event.Name)
            } else if event.Op&fsnotify.Remove == fsnotify.Remove {
                fmt.Println("REMOVE " + event.Name)
            } else if event.Op&fsnotify.Rename == fsnotify.Rename {
                fmt.Println("RENAME " + event.Name)
            } else if event.Op&fsnotify.Chmod == fsnotify.Chmod {
                fmt.Println(" CHMOD " + event.Name)
            } else {
                fmt.Printf("unexpected: %d\n", event.Op)
            }
        case err := <-watcher.Errors:
            panic(err)
        }
    }
}
```

When I run this on openSUSE and make a change to `hello.txt`, I get the following output:

```
 WRITE hello.txt
 CHMOD hello.txt
```

but when I do the same thing on Ubuntu, this is the output:

```
RENAME hello.txt
 CHMOD hello.txt
REMOVE hello.txt
```

and then due to the remove, no further notifications are sent unless it's manually added back.

Given that it works properly on openSUSE, this is probably not a bug for `fsnotify` itself, but I'm very thrown off by the results I got from Ubuntu. Why does it behave this way, and is there any workaround for it?

**Comment by dradtke** [comment] 2015-09-02 20:13
It should be noted that this is with Go 1.5, installed using [gvm](http://www.hostingadvice.com/how-to/install-golang-on-ubuntu/) on Ubuntu, and from the Go development repo on openSUSE.

**Comment by omeid** [comment] 2015-09-03 04:49
See #26.

**Comment by dradtke** [comment] 2015-09-03 13:56
That's interesting, but I'm not renaming the file at any point, and it's strange that it works as expected on one flavor of Linux but not another.

If I get some time I may dig in to this and see if I can isolate what difference between the two distros is causing this discrepancy.

**Comment by dradtke** [comment] 2015-09-08 14:47
Looks like it's definitely an issue with whatever version of inotify Ubuntu is running. Running [this program](https://gist.github.com/dradtke/c521a6a3aa831b3e6400) on openSUSE, then making a change to `hello.txt` correctly includes the `IN_MODIFY` event in the output. However, the same thing on Ubuntu reports:

```
IN_MOVE_SELF
IN_ATTRIB
IN_DELETE_SELF
```

Baffling.

**Comment by omeid** [comment] 2015-09-09 00:52
How do you make changes to your target file?

**Comment by dradtke** [comment] 2015-09-09 01:36
`:w` in Vim, though I've seen the same issue using Sublime.

**Comment by omeid** [comment] 2015-09-09 02:40
I am not sure about Sublime but Vim depending on the configurations may use Swap files. Can you reproduce this problem using vim with [swap](http://vimdoc.sourceforge.net/htmldoc/recover.html#swap-file) and [backup](http://vimdoc.sourceforge.net/htmldoc/editing.html#backup) disabled?

**Comment by dradtke** [comment] 2015-09-10 13:47
Does the same thing with swap and backup disabled.

**Comment by dradtke** [comment] 2015-09-10 13:49
I opened a bug report in Ubuntu's bug tracker, so hopefully they'll have some reason for the behavior soon. https://bugs.launchpad.net/ubuntu/+bug/1493413

**Comment by nathany** [comment] 2015-10-13 03:04
Quite odd having different behaviour between different Linux versions. Different versions of the kernel,perhaps ? Or maybe different versions of vim?

Can you reproduce the issue using`touch` from the command line instead of an editor? See #17.

**Comment by alexeyknyshev** [comment] 2016-01-08 11:32
Same on here!
Trying to make background reloader for lua scripts of my server and get this one:
2016/01/08 14:28:47.043753 fsnotify event: "redis_scripts/clusterdata.lua": CHMOD
2016/01/08 14:28:47.043787 fsnotify event: "redis_scripts/clusterdata.lua": REMOVE

**Comment by alexeyknyshev** [comment] 2016-01-08 11:48
Have found a work around for with:
Just readd event.Name to watched if received REMOVE event

**Comment by wangzhuzhen** [comment] 2016-10-14 03:50
Same on CentOS 7：
I1013 23:15:14.649953   9265 server.go:340] Catched file: "/etc/sysconfig/docker": CHMOD
I1013 23:15:14.650019    9265 server.go:340] Catched file: "/etc/sysconfig/docker": REMOVE
I1013 23:15:55.602021    9265 server.go:303] Watching file: /etc/sysconfig/docker

**Comment by JReyLBC** [comment] 2016-11-23 05:02
Same issue with Ubuntu 16.04.1 LTS

```bash
monk at BorgCube in ~
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

However, I don't have a problem if I write to the file using shell redirection.

**Comment by arp242** [comment] 2022-07-30 14:42
Closing as duplicate of #372.

**Closed** 2022-07-30 21:56 UTC
Labels: linux
