### ISSUE TITLE
Cannot rename/move parent folder of watched folder

### ISSUE THREAD

**Issue by huynn96** [fsnotify/fsnotify#356] opened 2020-12-30 08:08 UTC
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free

### Please describe the issue that occurred.
I watched path: C:\test1\test2
But when i rename or move folder C:\test1 it show error message "The action can't be completed because the folder or a file in it is open in another program"

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

`func TestMonitorFolder(t *testing.T) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Add("C:\\test1\\test2")
	if err != nil {
		log.Fatal(err)
	}
	<-done
}`

**Comment by cyf-gh** [comment] 2021-01-15 11:38
I have the same problem. Is there any solution?

**Comment by Vallasc** [comment] 2021-08-08 20:27
Same problem here!

**Comment by arp242** [comment] 2022-07-31 18:17
I can move the watched directory itself (events even keep working), but not the parent directory.

For example, if I run:

    C:\Users\martin\fsnotify> go run ./cmd/fsnotify test1/test2

Then `openfiles` shows the following locks:

    C:\Users\martin\fsnotify> openfiles | findstr test1
    364   fsnotify.exe         C:\Users\martin\fsnotify\test1\test2

And moving the directory indeed fails:

    C:\Users\martin\fsnotify> move test1 xxx
    Access is denied.

I think this is just how Windows works; I see other people saying the same (e.g. [here](https://unix.stackexchange.com/a/499165/33645)), and I've run in to problems with this over the years.

Maybe @mattn has any idea about this?

**Comment by arp242** [comment] 2022-08-06 18:10
I think #370 may have fixed this. I'll close this for now as I can't reproduce it, but feel free to get back and we can reopen.

**Closed by arp242** 2022-08-06 18:10 UTC
Labels: windows, need-feedback

**Comment by arp242** [comment] 2024-04-03 15:41
You need to create a new issue with full details and a way to reproduce.
