### ISSUE TITLE
No CHMOD on linux where inotify issues IN_CLOSE_WRITE

### ISSUE THREAD

**Issue by unixist** [fsnotify/fsnotify#131] opened 2016-04-01 23:53 UTC
I'm not seeing CHMOD events in places where inotify issues IN_CLOSE_WRITE.

**Comment by radu-munteanu** [comment] 2016-12-07 15:13
IN_CLOSE_WRITE is not handled by inotify, unfortunately. 

`const agnosticEvents = unix.IN_MOVED_TO | unix.IN_MOVED_FROM |
		unix.IN_CREATE | unix.IN_ATTRIB | unix.IN_MODIFY |
		unix.IN_MOVE_SELF | unix.IN_DELETE | unix.IN_DELETE_SELF

	var flags uint32 = agnosticEvents

	w.mu.Lock()
	watchEntry, found := w.watches[name]
	w.mu.Unlock()
	if found {
		watchEntry.flags |= flags
		flags |= unix.IN_MASK_ADD
	}
	wd, errno := unix.InotifyAddWatch(w.fd, name, flags)
	if wd == -1 {
		return errno
	}

	w.mu.Lock()
	w.watches[name] = &watch{wd: uint32(wd), flags: flags}`

`
// newEvent returns an platform-independent Event based on an inotify mask.
func newEvent(name string, mask uint32) Event {
	e := Event{Name: name}
	if mask&unix.IN_CREATE == unix.IN_CREATE || mask&unix.IN_MOVED_TO == unix.IN_MOVED_TO {
		e.Op |= Create
	}
	if mask&unix.IN_DELETE_SELF == unix.IN_DELETE_SELF || mask&unix.IN_DELETE == unix.IN_DELETE {
		e.Op |= Remove
	}
	if mask&unix.IN_MODIFY == unix.IN_MODIFY {
		e.Op |= Write
	}
	if mask&unix.IN_MOVE_SELF == unix.IN_MOVE_SELF || mask&unix.IN_MOVED_FROM == unix.IN_MOVED_FROM {
		e.Op |= Rename
	}
	if mask&unix.IN_ATTRIB == unix.IN_ATTRIB {
		e.Op |= Chmod
	}
	return e
}`

These eight are the only flags inotify handles.

**Comment by nathany** [comment] 2016-12-19 20:40
see #22

**Comment by matthias-stone** [comment] 2018-08-30 21:45
This is a duplicate of #22.

**Closed by matthias-stone** 2018-08-30 21:45 UTC
Labels: Linux (inotify), investigate

**Comment by matthias-stone** [comment] 2018-08-30 21:58
We're likely going to handle this with #173, allowing users to call the Inotify version directly.

Othewise this duplicates #22.
