### ISSUE TITLE
Error change in 1.5.0 when adding a file that doesn't exist

### ISSUE THREAD

**Issue by oschwald** [fsnotify/fsnotify#393] opened 2021-08-24 14:40 UTC
Previously, if `Add` was called on a file that doesn't exist, a `syscall.ENOENT` error would be returned. We used this to handle the case where the file may or may not exists, e.g.:

```go
	err = watcher.Add(lockFile)
	if err != nil {
		if errors.Is(err, syscall.ENOENT) {
			...
		}
		...
	}
```

As of https://github.com/fsnotify/fsnotify/pull/289, this error is now returned:

https://github.com/fsnotify/fsnotify/blob/e2e95171bc7c7402864e613c8b00a768fbcc2380/fsnotify.go#L76

Given that this is a new error that doesn't wrap the original error, the only option to check if the cause is that the file doesn't exist is to try to match against the error message. This seems fragile and is an API change.

We rely on the `syscall.ENOENT` error from the `Add` as checking whether the file exists before the `Add` would just introduce a race condition, where the file could be remove after the check but before the `Add`.

Note: we have worked around this by switching to `AddRaw`, but the behavior on `Add` could be improved.

**Comment by nathany** [comment] 2021-08-24 19:40
v1.5.1 reverts the changes from 1.5.0, but lets leave this open to review.

**Comment by arp242** [comment] 2022-10-13 05:18
Closing as duplicate of #144

All that was needed was changing the `%s` to a `%w` really, but no point in keeping this issue open and Add() error are covered in the other issue anyway.

**Closed by arp242** 2022-10-13 05:18 UTC
Labels: feature
